use uttt_engine::{Board, Move, MoveList, Status};

use super::*;
use crate::data::Searched;

/// A game of random moves where every position's visits favour the
/// centre cell of its board when it is free, and are even otherwise.
fn centre_loving_game(seed: u64) -> GameRecord {
    let mut rng = Rng::new(seed);
    let mut board = Board::new();
    let mut record = GameRecord::default();
    let mut moves = MoveList::new();
    while board.status() == Status::Ongoing {
        board.legal_moves(&mut moves);
        let visits = moves
            .iter()
            .map(|&mv| (mv, if mv.cell() == 4 { 50 } else { 5 }))
            .collect();
        record.searched.push(Searched {
            ply: record.moves.len() as u8,
            score: Some(0.5),
            visits,
        });
        let mv: Move = *rng.pick(&moves).unwrap();
        record.moves.push(mv);
        board.play(mv);
    }
    record
}

#[test]
fn examples_store_every_move_and_hold_out_whole_games() {
    let games: Vec<GameRecord> = (0..40).map(centre_loving_game).collect();
    let mut split = Split::default();
    split.add(&games[..7]);
    split.add(&games[7..]);
    assert_eq!(split.fitted.games + split.held_out.games, 40);
    assert_eq!(split.held_out.games, 2);
    for examples in [&split.fitted, &split.held_out] {
        assert_eq!(examples.patterns.len(), examples.moves());
        assert_eq!(examples.classes.len(), examples.moves());
        for position in 0..examples.positions() {
            let total: f32 = examples.shares[examples.range(position)].iter().sum();
            assert!((total - 1.0).abs() < 1e-4);
        }
        assert!(examples
            .patterns
            .iter()
            .all(|&feature| (feature as usize) < PATTERN_FEATURES));
    }
}

#[test]
fn fitting_learns_what_the_visits_prefer() {
    let games: Vec<GameRecord> = (0..200).map(centre_loving_game).collect();
    let mut split = Split::default();
    split.add(&games);
    let settings = Fitting {
        epochs: 3,
        batch: 64,
        rate: 0.05,
        penalty: 0.0,
        seed: 3,
    };
    let uniform = measure(Model::Classes, &[0.0; CLASSES], &split.held_out);
    let mut reports = 0;
    let classes = fit(Model::Classes, &split.fitted, &settings, |_, _| {
        reports += 1
    });
    assert_eq!(reports, 3);
    let patterns = fit(Model::Patterns, &split.fitted, &settings, |_, _| {});
    let by_classes = measure(Model::Classes, &classes, &split.held_out);
    let by_patterns = measure(Model::Patterns, &patterns, &split.held_out);
    // Classes know the centre; patterns too, and the centre's visits are
    // the favourite move whenever it is free.
    assert!(
        by_classes.cross_entropy < uniform.cross_entropy - 0.05,
        "{by_classes:?}"
    );
    assert!(
        by_patterns.cross_entropy < uniform.cross_entropy - 0.05,
        "{by_patterns:?}"
    );
    assert!(
        by_patterns.best_move > uniform.best_move + 0.1,
        "{by_patterns:?}"
    );
}

#[test]
fn the_weights_source_holds_the_text() {
    let text = "Ab+/".repeat(60);
    let source = weights_source(&text, "a test");
    assert!(source.starts_with("//! Generated by `uttt-trainer fit-patterns`: a test.\n"));
    let start = source.find("= \"\\\n").unwrap() + 5;
    let end = source.rfind("\";").unwrap();
    assert_eq!(source[start..end].replace("\\\n", ""), text);
}
