[package]
name = "uttt-studio"
description = "Ultimate Tic-Tac-Toe's adapter for the studio."
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cg-arena.workspace = true
serde_json.workspace = true
studio-game.workspace = true
uttt-referee.workspace = true

[lints]
workspace = true
