// Bundled by cg-bundler from the `uttt-bot-mcts` package. Do not edit this file:
// change the sources in the repository and bundle again.
// Workspace crates included below: cg_core, cg_search, uttt_engine.
// Comments and indentation were removed to save space.
use std::io::{self, BufRead, Write};
use std::sync::OnceLock;
use std::time::{Duration, Instant};
use crate::cg_core::input::{Input, InputError};
use crate::cg_core::rng::{seed_from_env_or_clock, Rng};
use crate::cg_search::{Budget, Mcts};
use crate::uttt_engine::search::PatternBoard;
use crate::uttt_engine::{Board, Move, PatternPolicy};
const FIRST_LIMIT: Duration = Duration::from_millis(1000);
const LIMIT: Duration = Duration::from_millis(100);
const SHARE: f64 = 0.9;
const RESERVE: Duration = Duration::ZERO;
const EXPLORATION: f64 = 0.5;
fn policy() -> &'static PatternPolicy {
static POLICY: OnceLock<PatternPolicy> = OnceLock::new();
POLICY.get_or_init(|| {
PatternPolicy::decode(pattern_weights::PATTERN_TEXT)
.expect("the pattern weights decode")
.for_plies(PLIES)
})
}
const PLIES: u32 = 16;
mod pattern_weights {
pub const PATTERN_TEXT: &str = "\
dicgZVifgUljXcWXolmealghadfZXYQefdXZiffdRkjkeYjegahgYcYTjhidbheeYdmhieQgecXijbbXWcbZaaslogszrrcU\
ehmcXTWbYSbgicVadgZTeemdVXZibQWYXVRmkjemsijaRgfgXYhgfXbwsvjYihfeaiggYUkikZlhadaciegVUljkbRVWWUYu\
preklfdYRfehadokmcTnmmhakfheo2vujPfegeUYXWTSihjeUecddRehheTbaecn3sxjUZgiYVTXfZUXYiYVejhaNXaZXRjj\
hcgjfeVYqqqibsnoePbfcWjtoogTgigeglccYUmjkdWjdgWSjjjgcrmlcVlmlchpfdaWmgkXXqmofRfifcbecdZVsooiVmhj\
bRfgfdZkjkei5vykQdfgcYYTXeUZZbWWkhjaQedgckoggdUdcaZbxrtkbmfhfZjfeecnddebqgifbiebffmelfcYZdbZgkrg\
eYdmgWaZYbfshebUngiiYrglbapjnhVcbaYfideZXslpcWkjjcPhjheQYWXWRVZXbbZdebThhjckynvjQknmeSXYbWjwsoid\
hecWWvnsiRVYZXQffgbRaYbWbmdgbZmiigeiaXZYnhhfYjcaeYkjhfZlgfcfnfkfaXbcdbgggedgbngaggteaadnfWeibZks\
hiZYokigVdcacUigdagslmehnjidcZZedaccohZbagdahfreedktbgkafbbljhjWZcceXhfhcbqnlaYcZdbfiZacVplieZkg\
hfZolkhZfgcfXbagdXgikXerlrgYhjigVdghbesimbYphqiUcZZcUnjjfXnjidZnjliRfhfcdibcZZwtunZojmcPcbaWTXbZ\
VSchhaVbYeZUjkobn3wwqRbfdYVbfhcf1vvqbfchZZvoukTUYWWRhfecVZZdYXbbecejadcXrklgZqnibWlhhbacgfebbYcb\
ZkipgjvlrjZdhbdZdcfciphgbVnglgWcfeaWlkleYjlfan2sxhVeabWUsmpfVhgffRdgfaTYZYbXbfdYVfmngnviqlThghcX\
cegZbjehcYihfZceZacXngkhdmhgfVYbcclqlgcUmghdaofifeskpcaWacbYgkliZdiffbolmcWmkmfZbcXYZtssfXjgjcPa\
bcZXdbbZj3t1lXYafaTmopjUWadVRbcjZSYXgaRYaZcUdbgYUsnslm1r0gSbddaVihlgl1ovgWXaZVTmnpgXchddSdhhfVZa\
aZTgcbYUmnljguqtgRmjihTeeffXccbbbgeadbwnsgZlhieWekjbcjgeckqhhbXonklWebccVjgjdclggdWabbZYnimmbqqs\
jXbbgfVkfgYbgfhdakkigceYcdXjhgfZedbgcpjohdniicVccfcjqggeUmlhcXZeeZWjhdZerlnebutoeaVXYZWdhdccghjf\
dopoeYbgcbYaaadkjdfeYjgedXefdfavqrmXdcacooflbXmlhbUfffiaqjmdXlggXbdedgVechdapmmegrooiUcecbesrpfa\
XYYbZclheZZhciYlnifdjlfbghcfbYllggYaZfeWikhagsjkbafdfcZmlkiZcepeYUblgYcclcnwipfazvxmYljheTknnfSR\
TTYVVXfWScfgYVVZfZl3txodedjgeegdgdjhigfbegdeokgfdfeleRUXZZTmlpjRgfgfVijldl3w3qSVXYXepmkdYppqeWdc\
faSYaXZXTaeeWhgneVghldXbXmaXbdffkvrpgs9x2sUtrrnTolonTjiifOaecdQXVZWfigifdefggegfggghghlZdfhbbnpo\
hXdgldpvqrjVdjgZVXXddZjhihZfcfbgljkienqkeYaddcZabhcbomlicbjfeVnmlgVhgianxmtgTcdaeVZbhYn714rVmpml\
UXXaXWmjjfWjgndVbbecouhukfZeggcbcjdeqiqffbeigghfggggghggggggXbbiXZpppibacjcZcglbXggiekzsxrWUWdbV\
beibUZZcWZaahhaphljZhdddXbfmfbiekhnnspvr0v4tWidccVfmjhUfeZgdYbhgcccmgbjkgfgegfjdegreeYepgggegigg\
figigggggdgiggfgggYdhmhWiehgXmgoeZdgkfYecddfegggejhjgcgggggifggegfgfbgedhbhhkjbkggdedbheceaeedmh\
mecdfkgcijgeccbledhhhfeeegggjgifdiigdYjfehZgeibWbkghXcgmcVejkgVkjmelyu0nUYacaUeikcUdfedbbdidcgeq\
fcjcieacfjfamkjefllqltyt4yXcbbeYfhdcaidddcjdfebhjmiYcffeajjidZdgjicghgedhiiiceeggcefdebkfohVabed\
ahgqjZdglbcmlmmsus2yWeffdWicfhceZcbXehigZkhicaeelgXggldcsljdbphicTgbccdgfkdYdcibXehldeqhqeeqlrfX\
akedYdbddaehkcVcimaYcedhitponXbhifZcceZbjfhheehghegcfhdddpgfehfgWjkfgWjjjfuvnwgVdiggZcefeekkkicj\
ggfcighecgfoecccdgWkfddlilghlnkpjXehfcZhekfYfdhgkrmjoZfefaZbgifegedhbiefacekkhZfgidXjfjkqkkskZfi\
jcZddaebkmgbbouqjWefddWdbabbnonidmgdcacgffamljfabccgZhdgfrokoeeuotfXgheeZfkhbaggmeWgddbZdcibXjhg\
hZhehejmoqiaiehdYjigdXedfgdjlmefggkgYfcfhickkevlirlYeffekropkXhggbZffZcWfmhdcmhldcefkebdhedbgiff\
mkiqdcjdhZVilhbYwsvnepoocRefgcUQUWXXZebhabaceYggjfo2xmgiwqrnThmgfZdfgfTYeYYo1t4oSlpmcRgjkdXggkcR\
afhbQWYXZVXeaaScjdhUhmleWfgefVhggZsyyyiUYZZWQeiebXeZcah5uzkOXbZZXtrvnNefggWslshl3zzrRWYaYdiefdZZ\
hffcijjhZZZbdcroridmgkdt3w6tWmjneVYaeeYcffbVYggaUcgfjXqpsjVVecdTgfejr2wxpSifgcRrlnjRcbcWTdhfgvyx\
3oTnonkUggigmzuuoXbbbdbklskXYWZgapjoddrjqgbpmfhaZbceipigfdgkdgUabcafqhnjYijkidwkmiaklhfVaagbYhdf\
cgngmhWbficXYighTbeZaTdehdqrpoiZnhofUYYbYRcedWYmjrcf2uzmTYcdZXcggeVjijhvvsyoalnnoVYaeaZihgcakegi\
ZXafcbqmlgbefmganfrcWnloiXemkbVcZegVihkfcoelaanjogabjdgYhfnfahjkdYdbibYfkjhZknibZbdffXehdetrrsii\
jjneZedjfZcafjZceehcjgqcZfghdaejhfYfffdqmsplXhdfdWkikfXjffakwqomXfhddZhedflpomlejmgkYeafcXlffdZZ\
adhYnnmickjjhdnjkgWfhcZXecfdoyuzgXegcfYcadbYhljhXfjjgwosqnWdcjfYbdecXkjnfYbeacanjgcYkggZdjjjbYlh\
lcYcaddrmtpgXdhhcXiiefaicfgujkinXchkeZhjcgUdecggmilkVgdcgdnikdhmkofbffbddkkjgbhejebchdcXfhhitlnr\
oYhggdZfcgbcZbcccbdchasspmegciiVafcYZqprjaiedeeggifekfgefieggXhegfXolkjj7wxpTVXZZTYdbbXiggevrwyn\
fkotjbccebafkgcbfbfbbfghfcllkicghdfafefdfifhgsrsyocnonqWcebhWigebWeggccilkkWhcffVdggfbkedkadcaad\
pgonXZdabWlnmgbiejigoolgYaZdcXkkihaddfjaijoicfffjdgeehefdieaXeYdbefdfcppicfnimdZmmkgbaehjVZhdbYs\
mhdaknjkXmlidWdcafdghjgehgfeffhhgeiggggeiggaYgZcYoknfelgkmXhhjidgfacUkpkhchkobQfkdeQecgacgjhehgg\
fhchigedgiegehfigfjdfgeceegeqkgggbeceZqfjfdejfhcgiidachdeTYbgYQZclYrugmfbbimiYahmhbfbdcfpjicXdhp\
eZYbeeSmmmhVifiZr0nuhTWXZXRgfgdXlkkZafbldihdegabgredcfpddighghgdhgdggdggjdlgfdeggVahehgnhlgZZVca\
WhglfamgofTfdfcjzhpaSYZbYSmjkbadfgccfaccgjjnbVkpphXYeicZonmktvnwgUWZYaShhkhVdebbgefihegeigdiffhe\
ghhhZhigbejagaZbZbaZbelkevonbchcgeacfedcgjkgefekbbidcdbifkichkhifidhaYaedfYiglgdfmigUmllmsyqrlTa\
hecVbfdfliflhadhfdbjdeiXkhhbSikicesmmcTTUVWTpjkiZpfgdWcYabWfeaYTpjieXmbiYQffheZrjmbTRVVVkxsqhPfg\
gaWskncZnhhfZlcjYUYWXaXnifcZrjndVgdiYcqflhZZcaYajclXYkcreZcdgeYgdieWZXhZjupqaXqfleUkficafgcdcujs\
aUVXTbYbedZVlliefrkmdZhdgecdakgXaedcZpllednkgeisotdVXYYdWghgcUgfeeanljbXhijaShhlcSRWUSUfgkaRbciX\
n0oviepineXXbZZXafhcYfbogcfdifWhgejUcabXennnpUecfgt1v0obplkaZXcbbZgbkeafglcelgicYcbjcaigkiWhjlfl\
mntgVdheZYdZZYWijhiWkjkhmrmmiZabgaZfddcXhkicklljjUbZeZakkngVcfkioqkqmdmggeWoljeZbXZYclkfbYplmdVd\
becYgbdfinfhbdgghgYmdkgalgieappndVWYaWcikjjXkkjeUdgeZZhfcedfaeZfolkdaqrohYbZdZigcfdegikgYikedWmg\
cZZfkfapmlmoXjjmgWfbbfitnoiXcbceVeccZWklkbXgefcmjadgXdbjaZjoehajhlbbpmiaSplidUhiiaZcbjaaZclfYacm\
aZidjegqdniTjhpmWmenarvuvkUjhlhUcbdWXecjdZbbfcXhgkjcvnrjXcddccedeifaggfdijmfahdfgbdiefegehqlsopm\
ZgdhibpjkZaphgaXhiicYfhdZanhifadfgkccbheYfhhihjjidgnkmgdjfhfXfhgcZfcddZXiddXfjgegnmiibefcbgodjje\
khegegdhgcdfifhcfffbeeifjmihjZfhfgikjnecgfhgecffgdigikehigdegjjdfkgjffijhdbfiicbiifhZieddgknjfci\
kfhcfhefbggddkgkgibhffijkfnfktlqhZppmgXcZbdcppqmUfemeaggigbcbeeahdgckqfmdbrlqiXjingWljegUXbedYhh\
hfZeheegigmhXbcejdhghifcfgefhdichkclopjhojaeegcqjsplWdcccVgdfbVkhlcVecfcYkhhaflaocbonldTfgccWdkl\
haiajajsmugVdfigWedeZQeifZXkmogRcaZVQeeiZn0qrkZmkkbbigedYegmhejglgehggfafdjfbbgaeagdfgWcgdfXiggf\
ormrdSiegcVhhigatulgXffidnmnpjYkmkiYfeedZikejTbcZcWlqfdahbnfbhfiiYdicedhlngVgjifXidedXfjcfqjomkd\
eehhblfgjgilmgegfhgjggfjbfihheebfdphihjYifedYjjfXYhhgedjihgbgekaVdbeeRjkhefvqrgVmnnjjsloaUfeefVh\
mnnXffdaWdekgcjfmfZhcleWagcgardpfamihgftdpbWmglbTgcedXnhlegkkkjadenfYecffVefhabhfgbYcfdfXffehfvh\
lkWWbadYmkoiXbZdaeursnapiiiahfjeWbgddqptpjYhldegndldcfeedbffldehifgYehmaUjnhiYaZfbZdieeozqvfejfk\
iYcdigWdkkhdgcffagiccbhghcZfhfdrjfqlamhmhZdhbiagghcZefjfdgigcbegghnkhofZebgfYhffeXnjliuogqpahgfd\
egqbiphjklccfgjbghdcohgliXdYcdVgfggjqnliYknijbcccgUeihgnprrmaldlfVeZabdhmldaifgcahkeddfgfdYddhbj\
nmndXldfdaheogqntmkVgfhjVecbaddkjdYkggecckghZcegfbikgebjjjgbfgckdglhfdmoffYdedcUccbdSiklarurjgVs\
nrkXljnapxrsgRUaWUQcedYUkekcXgkgcXaififheaahskkeYpmodZYaYaUjindptinXPSaWWVpmqgo1rxmfjjhgSZbcVTkg\
leRehebVYcecdlighZehledrnriVcaZXZeeffomececifgcaioldWhjdckskofTahebTfihgYqlldckefbcddbgbongialgi\
kbcbdoqtvywfginqUcbdaUeehdXcfgjepjgYesilgScjdeVaeecbfdfcanhlfYkloiWbdZdlnmqdWcefdaghedZfgagdqhnc\
ZmdejYehggfnhmfeddcdbededcjphgdhlegYccffbmnkiXihhcWnlldVeckfagglcSXeaYSbflbiqpudWnilfWihiZjyqrjU\
kkjhWaWWYSeeecUcbeahsotnacghcZgefdbkjgiWjghdZcekbahihjntoljXeeidcilikafmjZbdhedbheggYZbecZggjilp\
jpfbljjliljigaeiedWccbdYkiieWchgdcheifWgdbhpmlniVlhecZbfbghjfleihkiecghkicffhdaiggdphhfjZffedcgg\
ehdnjmgYdcdbfkfficghgffgeigZaejeVdhkeuoccbZkjlgeccfechhkfcdflfVbdcctujlbVefjgdjgqhhkgkgZcjhgeddb\
fbdhmeabllgccdleYehfdjrkmdXfflfXficbchblbWXcfZVhhodqtjoXVcelgYkkreYZZiZbwsrhafaecUedfcYhemhZXefc\
TaghdlphpdWhehbVnmlhXkfjdguoreTjhffVqnpfYTSSZRcdjcl6v2oTUXXXVkoifTdggdVhdndi4xxrRZdfZTVYXYSehedW\
votmXqhrkXeebaWnhkfYaaWbWmnmiYojigepmkddvpulWXXXXXnkkeWhklbXhigcUbddfcldbeVhonecskqmfumnaq2xwmVo\
jneTTQUXSdedcWsmngWhiibivnwnWYcbXVgfhdVfmjgYdejdgeghfgggfgffijgghgfgjfgkhcejeecgfgdenfljfgedfeeg\
fdcikmdZeZhejngjeZgiidWhfhcbjakip3s0lUkllfVTXYXVmimfUgfleWeegdf1stlaZbXZTifmcUmiofWglichofneaVbf\
caefogZjgjbdbgkcbmcfcbmjkfZihhfdpkidp1prhYbZccZjeifWhgkdYdghcefdfehjerecghihbfdfgnggjecjejgdheke\
lkckfYhkciafkgcWdZbbTjfhcYXcXYWjlgYZrotnhsooeWedfaYhYbbYmnogVmnlhivlniduoumVUZdaVefecZtkqhclglca\
ccbeggbabZlkijbonjialihcZfbgeanmnjcihjgbfdmdZidedYijodcjlhednglddounlXZZZZZgeccdskjidkikcYbZicWk\
fjeXlkokmllneajhjaXqnmaYhlmeYddehhthjgZflegddggeakiieu0w1rXdcjeXlgogWkhgcWdgghZZadgYcbgfaijffeup\
uiabhmddiggfdghjiegffgdggjfXcfkfYeihfhokkeXcjkgn1rslXgfdeWkiggYgfikYifidejgjeahcheZajhbdhejdelik\
fcglehilknfecbegcZcddfkglhkkkmlcjglfbecfielcgddlggjchgfgedckfbggejbhhhfbhffeigmhdjjfijaglfgddege\
ZiggYdnsohTbfgfYnkjdgonnZaifghXjlgfYfheelhgoex0topVdjhcVpgogUkglhahedceehheggfgjZihhjdgggeegghdd\
gjfgbdhhghgilkXgfeesqhleXgegbYmhfcajfmedkmjcaebffmmehhcnllgVfifdcvlvmXccdhaefcdTaYbbVfjdeowovkjp\
nkeYahjfZfejfaeegkbcgdfXehecXkehbZhekhurriiVeggfUiiieSiekdnurthXfekdpqopkdgciefgfmfbebicVgegcXli\
efcknirdijkednlkbWbjfcYqoomYgfecnwltjaklidYobnlZbacgdnllkbddbcbcdfcZhfkgbqhogagdfbbmlngXhdjaXnij\
ebmgkgkmdqgYkqliVggfcWecfeVfhfgTcjefWjjkctnnreejgngafekhcdgdgfhltebccfgkjhqjcifgfcgjmiYddfegghjg\
cffgfgefejddehckjhgglnionehdgdehiljZdegdbgihhdkjkkdiefloqquiZefhkZdfhdaehifbfcgYWkndhVbbbcZfhkkd\
mhoihglmgcdkeebefefdcfpgXgdbZUifkevhynlhmhpjZfkhcbgfecegffhggecfdmghkckjfccgglhfegfgZjidhdiijfXa\
ZadZadaaYrnllZrmxibmjidWbjiclormiamffkYjbjcelfegegegegfgiigijkeYceebllqlmadfkebhcfduitngVifiiTje\
jeZkgfgafgjghdjghbdgbfakhgejjhfjcieedchkidegkhjcfigbcdfqfdbandephggcZegfYhlijanemdZhgffikhdaYehg\
bdsilddmcfffegdfcoechdhhdgddeegcgglgefedeehgpgehglcbejefagekkegehdbjfdgesfjgdjgddbmhgcbohkddbfZc\
YskjlZegbdaZggehshpgdbZibblgofadaeeqtrnjaedjfZfZjdZgkhcbdfhhdkgfgefglgdggfgefijgehggeYghkhahffff\
fckeZghjgegcjfhhggghgfgggfgggbdfiecijafefnkfdiegdcfihbdehmfcicgbdjfhgbokiedkgijefcecggghedifigaj\
ifgbmfbdbfkidbjdkhaigigeniocZacgdYfhleadZffrtpkmVheihYeZhcWnhgdWhhieaghdcdqedccgbdffighcZaYccbhd\
pbbehhiVhfkdimghaXhdghYpgdfhtpsiYjjljXdbcaYlhkddfegahhbehdgdgdahknkaedddYhfejYcedbnsijfYfgjdckik\
ceffhgcgffifefggdgfmgffgjgaefcggkdfdciiilekfgderkqiYdeebdhahdcjhleXafdccfkhemjfmiahghkbgheedgfig\
egggdcgeeedhgjgbechdchdgcbngjifggggifgggdgihghggggefefdcdffijhghgakjegagbigchiiibhgjegfcecbicidh\
kghgcoljbXfhpibjcfcajhjeZdecbajhhjnmkngYgdhcXceihYfimgahadadhhphecaffaddkaZdhheekhiffjimefiehfah\
ligcfhhgamhkeamghcbfZddUlklhakdfcWZVdYUjfiabogmcbiihcajaggZebYbamhkcbkfhfeiejdZbaddcfjkdbhefhWde\
ebdfdcYVhlefanhjcZehdcaohjgXcYcabrprfYgideYfciZcicfcZlmnlagegbnqpliYZbfaXhimeYfcegZccgcYiiqeffZj\
bXedkedjfjdcncmddkbbcajihcbkegfZjggdbgbffWgdhZbjenhflehdbcgefdglmeZgffgakfjbbagcccbdliadedcdigjY\
YkkmkdjcjecfffgegjhheifdhcifhfXhghjcghkeZkiiecmmhfWcYYZcvjjcbffecaecidYkdcdXgfjaafiigtqupjTZbcdX\
iekdVkfjhafgiZYdjhbelgkgeigebbfegbbfchgelefcajgdidjehdZiijhmjpmkYcZbYaigghZdhncbjeZgYlnicdfYlhgf\
jgddfggdgidggbfjiffggeejnhgfbfilgedecgfgggggggggghghgggggggggggggggggggggefghhciffhckgjgdgefgcfc\
ffgihggekijjZdfgiZedgdegkggdggggfgdggdgfgggfioggjmhgegchgdjhghfggigeegggfehhgeggigfhllmnjrjkbegh\
dbfegbdeiffdhggeffdgheggghghfidakejeagbeeddfhdhhgikpllohYgfihYhcfhajhhecfhegYlfdeeiiigegdgfZmimj\
jmhmiZggeaXebeaebhjecdhgeafkgiffljedggggbhfjkdfdgeWefkkbhekgZdchceihkdhnfehcdogfZfaffbihigaggijf\
gifcmhjmjaijgcbeecgcmhjfbnifgbjfilbegcfZggffahbjfdlldbwivkkVkfljVechededfighkkeaffcfdfejecfchefi\
egeXdfedpjnliYhfmfXhehhVfgedgihgcblgjgagfebegkkhZgfgidkfghcdhhgZhgjekklnhflflgcghfgbdieeedeehagh\
idchhljdegifehfeedeefhbgghemhnheZjejfZeegfZghijnjsrkZleifdgfehmljjfiiggjbhgkjefdghcfieghggggejgg\
gfffgheggcgfgfkihgfjhafmmdbghggagegfvglfegikefcgfihcgggebfggfnghihdeejfafegffeiklrmkmdegiigiikgg\
egflgdfhdgbfggephfkgXihhckllkcZjhfhWdceedmggmWdeceaihihapjgjfjjggaeeeebgiedYdgiiahfeZWegffXidif2\
ithidmnffejjiecjgkhdedgZfhhkmjhfgjZgfegYgjkbadfhZXgjkgouopfjgjjecffdfcgeffdfglcagehdZgfggolkihjv\
hslYgachdjjjhYfchcbiffdYjdlhgkfghfifcdedjjgafeiicfgjiggjjedgegghghhfdgihibicgjigegfgigefcjggghfk\
deZggihlngigishrkZdkgfZldjhZchddYigmibjhgechejodjindecfigaeccgWgbhezglijnfgknahhgfbiiihcnkddYkbg\
hWfgggYidfeZhldhkjxojZpegeagbceVeejfkrnjechffbZfhidZhiifagghcceiifogpkiZdedhYgihiqmkmmYgeffZjedg\
tdwpjYfeefdfgigegheefigejcgbgdahhhhcffijimjmbagifiefeifagbkhcfffbcgdglvliofZghidedjhfdggghWhhfgj\
gfhhchgddYfghguhglhdggggnjcoiZggghjjgjhahffcciglbfpjleekekeZfekdkojogaecfceikgdcggfgggdhgZfigiWi\
cffgohngchkhfbfZdaVjehkqglheffdffggiieeghihtgnifUkbfhXbfdfadclbk0pxpaYgZeVdfeabpiidTdkecZcdagYqn\
kfdoklgemhkcfoinkbdYbeachjedcgiebfjgfcbhicibcgedkekcemjhfadidfciigfYpknicfgbeYedjelmpslZedccafkf\
hafaeghtgooXgdebcfZeeZjikgciZidfmfmjckimfchedgdgehdebddiYddiaYgjfdntjngZidiicjhieZjjoefiilcbgfjg\
cffffbccYealjlgmmdjeemllidhdhgbkblgcdefeZifgdqnhjfYhjgedfbffVifdeuqsxuVZZdYVfdfheqnpsapkhhXcgcbZ\
ZaZecnnkgdnfocovkqfYedacZigiegklhgYihgdbegjcbhdjiqjoiddkjidboiobecabdpjloqbgfdZbchdgcigfjSjghbZn\
miZWchZZVokoeklnockoipjbghhbYZZYeYfgkechijfZkiheeedieZjghedojjjepntmYgcgnXZcbbYflogYecbcfgmnkXej\
ccYmhjfYegheahfjgikgkeWddhdagildcceggbfdmfciggfeggibfifhcegfhecegmgbjdpdafhgcajgkhWfdceihemheggk\
daiahfpwrynUiigdUXZYZWigggeojogYlnkmUbaaYXikldYjiohlohigabZfaageeghqljlWfedcWjlhhriljevmetkZddae\
adkfbbffdfVjgkfVkgjfqrsmfWcfadajfjcgnmljakfqfYjgejadeeZXlemdpqimcXogljXeahhkpooicfagcXggehZdhgfY\
gghdtgemdXjindXbjkcYVabYYghgdjlhgfZomogajhhdbeeedmljlaYigkjahkccchjmibgjcbbhbihYgfgkUbbgYSkejirs\
logiiiulilhjgYcdibZgfcbYjfdknnkokZkecfccfhgimhnhgkkjjXhhkgXagfdnhiogYifgfadjcjXccbfomiviVgjniVcf\
dcoiijcZgjkhbiebbpjiofZhhdeYcgdgTZZceVfeedWZYXbZnmnmgslqgWdfgZdedefYjjmkcmnlfaghdbcgXbeeelichlhm\
lbdcbeifgfgckjkidlfkcdgghbcjghfekcmheidjfddfgegieikahfbhbgececgghgfiiphafdgfbhkjgeieifchjhgbgige\
ffjfebggkfkgmhfckhfhdgeiffehmebgeegdlihgbeghgchgegbigkecdhlgajhejcbefeaegghikgcgefjfgdfhhfbkofgd\
bcifbhgigrjfjjbjfghbgfdgccggfbgehdilgkhcedgmfjfgddjjjiccfffdghhfejhhfgghggggggggggfgbedjkmnigeeg\
bhiejkkedfghghjkjlbgdgdibdhgYggibkpmqidjfhbcibbdcfhghbegjgdehfecjgigfffldfjcmidfgdhdnfjcgjflccef\
fgbgeegpjihjdjgggdffgfrjkmkadgfebdheefhifhcchhgcdhjgeikhhhkegdjggkjgeehflgfggdggfhmlfgiegggjdgfe\
gadhhddijneakipghilshajjkdacafebicZeckcmfcfgpdYbggidffdddfgfidggifafeegcihdcdjdhdcafelgkgmgZdijh\
ZecgdebinlZgdddfghihgijjgbfgejbgejeYbaaiYiknfZfdklrurwiYhhbcWgeidrjimgajjgmageflajjpfZchgikhmjig\
fidihihefigekfogniefgidicfbigafgiicghngaecigrgelfZcgccZcjeeljmpmZeffeageccdkmkgbhfkgcnjihfgiijhg\
hihbhigibffghcdgeffkcggejggeiikifdcggfcfdgdckpogfgekdrkighcgfjfeggecdggggfghfhgghigdggggjhgmeigh\
ggbhffhaigieVdbjdXjkjjcehjdZlhnhdheiiafehgfjflgahjfhdliehmgkhdbgfgkbfdhdZeehgcijjgdfhlfdgjfhlfjm\
icgfefcgeigdfgjgfgihggjhggdfeggrggjlefdfgcgghgcjehgefgfddgejgefifedhhfgiigigegiggfggfgRciekUZbce\
WnkkhqprmokkggiZeddeYgbfdcmkokWjfheWhehixgnkknohqmdddgccgihdacebeaehfefijfgeehgdRdhffWhikfreipkf\
gfgecgigjegcihbgghgpmhghnidmhdjjhfcgfdhghjgggfcghqjhnmZhifcbfefeijcjedggifedgighhjfgnhnifZhdedgf\
ihjXhgfgngghflggjgeggggdgfhgXbaccRghfYmyvedRbgbbq1qqdSchfdYskrfapolhgghcdahfkibXcdiVVaYbWghmYryr\
scTbecfWvqriUXdcdUceddtzprhTceaeVkpmfXigkhXupqcfhgibXgcedXnlpiWXXabbpjjiZiihZgmgebZlkjgZbfebchgd\
cVeefamqmleVdigiTeecgWpipibdacblqpmiYihjicgYefklggfVjijfegeghmenqgXigieagbcaZmjifdjjhbbpmoeYcdhd\
ZZdbhoqlohVhigdUigdbWjjgedlnigcigffZfhcfiehfgigjmgZgegdekheeZfjgcUjkkiUdekcXhgidkfkmhespreYggjga\
bhbbYifhdWjjhbXddidhslwkagefiYgchdZfdejdhkmggjejfdejhmWdehdpqooiZdcechojpecihheZnihjXffgeaeffgah\
jheafdhdcjiflmhiklcggcfakgehfjikbbjkfjagficefgjgeeghfcifgggkiklbdgffdgfjfdgihhcfhiebkhjgegijgcdd\
gdfgimeakgjijgdedTdfdaZjeicgzu1rYbcaccbiedcpjiganmjgeebdfhmmoidfgdeefbffbfljecfffeaighfdvqoiaeaf\
eYiijcafdfdabfcfalggdatkngdegeZXfgcgbnlpechgkichhlekgceeZjfggblffheolefcsknfbeeefYegdjbfeigcjllk\
ZeghfbZcZcaijoicjflcXilcbblpmiXfYbYUfgfbvyqwsepiodbgmifacbeecldgdYbcabXfjgfrjnphZcehibkiieceYgbY\
hkjdltkoefkfgccdegfZhkeejjdmbcjjjgZfaacXfjjhsmkpgZadfeZkkigqpspkWefhdafafgZhkhdeqmqjijiiaYciefcc\
ZddXbYYcXkjjhlkpnhZhjheklkpiaidlgadbfcdmikgcgjdfaiejjcdchdZjlgbbnlmiiojidXcgbgYcccfZgljglkelhXfe\
meZdadgUcjfbbiigarrhqeXddfdaghhgfqhhdYjiggYfefZejgmhghbcddjgfgbbflfegihcmifmfWggkffighbWbcedaleh\
hnujnaVkkjeYhgfaaekednlcfiXifliWddnechikfskklgWhdkeVcgdecmgicehdfaajfdccijfgabkehghgleXegdhhgfhh\
ckejedebgfcffkidhkigbgeghcgdgiefegfajiedcdcicbkhigeemmffjchgZfkkjfeeefekgkechfgicjegdSZfdcQhgiey\
ohpfYhbihnlpneXikfdYdceiZhnkdtlhjgZjckdadegcdcedflolnlbgihlddddgpngklYegfdcjeeelggklbecgfahfidWa\
ijfsoithYhffgWYajbpjindbdjjkccfdehqlpeUmgoXVYZbbVmlmeVfbfXcjingbccffYhjkdagfiacnllfapjkiXWZbaYgk\
ebammkcbhihgcdjchbjihggmmhackiljVbXfbWgfjlbijjahhmmgabYdeaihichmqogWghkhYcefcYhfeholktiafehhbgei\
ijkfmbblflcWikjgeiaggVjmoeZdeccXcdghqojoiXghfgXkhddaciffhljleXogngWgbabkhZkfYigjeVfgfgeihdjcjdbf\
ZghffajfjeogjgdZgbfgchfjgZfgjdZdgidoojjpfgfifefffgihhifdiifgdedfgbghjicgdiefhgdaljfgdkhigfgggeic\
ifffaegfhflijhcghhiefegfegghfchgigegelhefggdegfgjngkgkcjdidcffdgfgghgfgiggfgfgggggffgffgfghhghfh\
ffggjiggdihggfeggfggggggggggfggghaedkddhgnjcejdchkhckegfejeggfgehgihgghigdjfggkggkhYcgdfcjemgbie\
hibghiicifeilikkicihhfdgeeiagdhcdldqdbhfgfYhhjgZehigjfhjhmggmhcdfgfcfkgejnmklafekjbbidgbheffegdh\
gcggggflehkZehedpmjrlbegefciggecigffcfgfgkioojZedlhXdgeialfceXfghebfkkkniahadgjmfefhidcggfchghgd\
hgjhgfgfhgdhledZfggfqknigcfjhfegegeppnpeVejgdXlhooWbjhfXghgiagkfgggmjgfggjdlgmojdggbedhfjdddgfej\
ighdZgigfcgheeZgdigfdhkgceefdfndiddkighaegedkinjhcegednghgldgfdicghgifgdeegimjfbgfhdccifehhcleZd\
bcffikjjacgbeZkjligjjjceiengbhfbechjhgeiihdfjegfejggedghegdigggefkhfbffegcighjgjfddceghechhjebdf\
fdkjjtifkhigakhebeeiggbjefglejfnbehdfaeeifcfhgfnnkthbegdgehlgkmglgfeggfgdgggglggggXcfgdbpkoeahdd\
dlhmogaijjkYhfcjrkhekYgkhgXfhgecgfjidgfffcgflhXbdbbhlhmeXjkikbfehabhfkgYffkcaeilgeigfdYgkhfeghhe\
egclhejgfidgffkahffidedgioejohdjfjffcfddfgegjcfgghiefijbebefdfkmfnkkkiZjiglogkgfcgfiengggjahfied\
ljkcYeggfadgihoffggdgiggdghhgdgjbdfigmhcgjceeefmfehgkeeiihhdefgjdicfgbggmffkjihhghigdidgbjgdhgdg\
cfgcgfginggjhhgjgfmhdgjYjojgXZcYdcwqmdbZheenskphZheZidfdecbcgegcfbeebccddepmmicmfdfepimjbdfcbcmi\
kdddeegcljjifdfceeZhbcagdedikfggciidhfnmjfdghfgeolnlbYbedZgjgkbZgkhirjujWdhldbgacYbjkhcXhfegWhgi\
ffropmZYfZcVmlkiWbeeeehqfhVifgfYjkjfUdeddYgdhhXqkhmkgdcbTdeedmjjfcfjgkfWjkldejlpkaYecdYjijgcfdfa\
YdjhfXeefddojgeXdedbdxgomcplgecgjggfecadbgnigdfdeeadfigaldkaYnhjgbigkfZhjdggihighjhkhbfchfeljige\
ahegfhihfbehkfcdchdccdeheliniaokmcbhgiigabZaZeddeepnkfhcZcgZmmlhafbcfjjopfebdfbZhhmhbedicYeeceje\
cdbdpjkeagekfWkfedZggfgccjXfXqgmfcldejWedccbdgcbUjjmhalhgfhknlfaahcYZjkleaeghYbmhqnXdbfXYgfkfagf\
kcVkjmdfkdYddjhfhejicdflgpeaacYecchmechkeighdfdjiliehlfdgUeddfdbahchokqhgihgebgihcerlifeijliecee\
dcjhkdcjideYcdgcfjejcWgffbelgneYokmfecgedageeaYjgchcYeddfjloaenhmgadfdbeegjcZjikgahgfhekkjfbgdhe\
ejfhfehficfbgfaYfgihemhdgegdlfUifjeefihYaqkobafckbcgZdgWsiriVXebalphmfddgffafiihZdfdccpjmfZaZfdi\
dcgfYfkkhaknhcbceedfkiehbkqgecigifskmqogdZgcagigiXeffdrqmriXecbfWhhjfZhafdhsijdbhhcdZdggdafjegji\
ggfXiihgZkfkgfimegdffifgehfgZfeggdhdfgbdgggchgliafekifbigedsflidcgddejfiachjfmbfeiifgdgegfbggejg\
jjekhggggefgfgiedhfjgjYilnhZcdZgekkgideghfhgifgdgggkcgifgceefceihieqfkmgdgbfecmjhefdefgbidffdifl\
feefhdbggefnigmhaficfdjmmjXechgbcchdfglkgahcffbfgecgifngUjdgfqtpqiVidikWadZbdkdhetipggbggdgdggie\
XeifgZdehfYgfjhsidlftmnhlTeehiSeecgbdkfgYigieYiddimkiofigefgcgggicgjhgcghfgbhfighdgiiffhigdfgggj\
gglfdggigfgejfckfgfegefdhfhfephdkghpnndYcfedbecidZfgccmklkkbeijdceehhciglhegkeccghihgkgggdeiheXm\
hnfhjdgbWggffglkngaggchXgghlnkgmfojjjkZeeegZcedceighgefegfeghigWddidkjhqkXcfcachcgehhijgbedhfhgg\
ggaggifZdigebjfffgjfibZeifjiggefYbaecYfgihYgiihYefgeqikfodhdgicikiiZgfhidgeffhnjfeffehjkhgkfgggj\
fnghgfcgjggdghjgYehdffkkjaZgeeiqhflhddhjeZjdhfritnjYijebbidfgchlfhbihgfgmkoaZchffZfchjddffjbgdfe\
dgiheejgmhbjgigadegigiicelffgijehmjagfgeujqijVghelWigfhYfhgfmgekheebifchhihfkegbafhdgkhkjhdgiggl\
ggkhffhfgfggigbggjgeelggfiieihedhfdgghfhhghgfdffgfgghggjgifmhhofdicfiabhhgcdhdbgggdhfhjhgdhgfgee\
efdddcigfdgggepgghdkjgfZfhfidffifZgfghggjgggggggggghggggggqlghgfgkffegfhgcdeficdidejheiiaeidfgff\
hhfghfgWfdigbmjjhYZdgffghhkfhkjhegkifVddcgcggkgcgffgbiffeaffhdghhmgaghlfllllibebggaecehmiihnamei\
iahcedifjggYhcegdmfigZbhfhegnbffqfmdYfdedflkefbhhmgYieaYfgiggfggkcddfggohmoiaigdfaiccjYbfhgagikg\
pglfglfggfdfeggcfijfWfcghqfjehcefdeolgkicfbjcvkomfSfciedgfefcjfheggggggggggegdggggejgegiggdYichh\
eighclkegajghejlgkaZidbcbggedbgZceamhgbZffjcfohgimphmkabcjbafehedggggdggggcieggcihdihgcffbcedefj\
nkggibjefdehddgehgcebeecjemcdidhccdhccZgbkddmffgkgjfjYgjffjgdjeeggjedolheZojibaZXadenkkcdigfaebb\
ehgqgifbhnkgaehcebigjfdphlddabdeaicfkdicjbbjgddYedddbifjeojkogdlejfbhZeeaegigajfnghlghcefhfieghh\
jcjfngWZXdcajhdahikjeXcddWZiaggcijihacYdgehhfgjkelkZbigghgfgfchihfdgekeclnhecfdefcojegaejdjYdhhc\
iklmcchhggXfchcgigicchdjccgfgcgdjofefeeidfhajjmklfXZXZYbmiijbichgbeeeZbhfmgaifgdeqhfhalehdciiddc\
eekfehffgdjhffcebkgdggggeihigefgfdfghjgfgfgifgggedfiecbhfggeihigeafjgcgfhfjbgigggeigbihgfYfkZgYg\
hgilgggjdgfhfehghgvglkhXghhecmfegVhahbejgddfhejbfgeifffggecdgdhgfhfhZklgcclgeZbbhkiinfmcYhegddjf\
hdZgfghdjiejdgfggchfgidhiefdglggnfhiffgffdggifhagigeaeefcmjhngegfgkfgfhecgjhebgejhZhgjdingnbZlhm\
fefdefbkjffjdicgckibkafeffbfegjgihggdgfgdpgihhfgjhfcceebeicggdgghflgilgdgdlgbggfhkhfgkacfgddjhhg\
afhjdhgggiUjfhgwjpghVgaehcdcfehgkdgdjlhgachfdngimjafflergmjfYfdffgeeiehihgdbjgiicghhfajcigpgmlgV\
hfkfQcbganwhsiglmmhfnenbXaefcWedhbWcdbYrslshVjhhcWhflcWahdchgdbcfrjlcaaZhgjjjiZVfhjeZhjigVbgfcYX\
dbddrkkecmjickhghgiigjgaeefacihgfedeggflkkibfflgmmfjcbgehfZijhemhklfXhfddcfebeckilgciiigglihfgfh\
ifefeigohhlgbdbfgZhkhfbqlkZZddjeZeifehihhfcjgheeecngbkehicggffbhfefiglmfhghigbgdghbigbgmghigZdfg\
fngjgjcgcfceggggggggggggfgdhmgegggfcdiiggejeggdgigffejdgdeiidbgggcbjhekbngefcgiegafggedghgfcihik\
ZddgfbifggfifkgcegeedddedijlimciiihaicaebighgbcdgghhehcihljdbfcjibeafdYledcggggggggggegfegfhghgc\
hgnjcdafgbfghfdedffeglkgfgeilgiedffhihgdhiigegcgfbfegfehfiifejgeeihjfcjkjibkefcZdkgfchgkfZgcjeZe\
giefgigffeeidYggleYefieegfkgdgighbgefcihckfehgdeecghcafiigbfXgecgdifbffdccidgffikleaefcbogfpeYea\
eddhigafggigfggggfggggjggggggggghggggbgggfcffeffgghgeeffgiggggjggigedfgepgghiagffgekghgeggggfdge\
ejghggbgjgfkgggfchfgfbgffdbgejfkggiedgjkgcgegbdcggebgfjfagifglhgmgdgkhgadfdgfdfegljjggbjkdiagbeb\
gggggfggggfgfgfcgigfkgiggZhggdrfgfgehcidlgiggiggihlghhgbhjggkkgdhdggggjggggXfeefejkhbegggdhjgggZ\
jeefeeikefgheengfjghfeddkhfjlcgdgdcjffgegihldfefgZefaibidleehdiehohmgbfdieelgmfZbZedeogjhbgglhaf\
igfYgbcanlkjocjekifigggffeegchegfghegeffgeffhdhdeiihidglgffggddfggngZigfgcgefdclhghbigicjggfbfig\
kecehgffhkhhcgdedfgqdgaghifdgghgeffdfkhpihghgliegfeceifkfadghfnhhfglihhfigjjnadeceigegfbgggifeci\
dcfflhhflkfbfijeaeaegbdcgcZfcfjmllrhbedghggehcfhhpicfeebdggigbmdgcchdjebaajdcigikaggieabegimhflf\
dghfggfgfjighlhegfeeafbmkcgejiZcjhaejhhddimigYYdieWelgbdfZednrprlbheeddihiekhfofajdgeaebbimfnmge\
gjggejchgfgejjfgfhchhdifegejffigighiejcfgdighggihagcgdjneoeimiieehgdfigfhgfgehdfkehfbfeghagfebpl\
klhbfehgceggcpgfkheffgfgdfedggdpjefifehffjfigchgjjgjfZfjeefffdfrejmgZfdjgjiekhehggggghggegefffeg\
jidgggffggkifghggdgiggfggigfggggegkggfgjggjdgijfigggchhledgefeggfgjfgfggfggggfggggjggkdYfhcgcjdl\
ledfmefidhhfgceeifgihfgghfhgghiigfjglgghgigegdXbbfhofmihggggeehgggegjggbgfhdfgfffpggekeegffigjge\
igigffgffgegiggkggmgjgiggkghjijgjgfdgfghdffggpigigdgeggpgighkgghhiggkfdegghjhgggfeedekgigjifggfd\
ghggffggglfgghhghgjfhggfbgigckifjhjggdhhifggeggeitjgcehghkecibfhbdfghogjhhdghggmfiggkgfdfaheghng\
eggfehhfigehglggggeghhgagjhfghjkgcgfgfbdjjggghgdbffegbgigiolgjfaecheegeehgiiigdffigZfgjdlilkfecf\
ceejigdggdigffhghdhfggheeiedfhhhcigfcmfjlhabfdcihfjgcfffcfgdkgdfdmgageefognfhZhfifWifikdkhffhgjg\
gggeggajgjhbcghbjdgijdgfeggjegeYgbeeZiehkrhgkhgggfeXggielfcffZkgkicgjkieqnnlZadYcZdicbgglifclifj\
dhhcfcfecfegefgkijmicgefgaddhfdihgjjdjgecedijZhgkgingjgaZhgcmkkgjXegdeYefjfaegbgbgddekhkchdingjf\
mhjfahihffgffgegcddeedfikkhjdcifehbghfhnilkbbfdibaffbeffgjjdiggiYgfgfjfblmXkekainllfgdZZgehgicgh\
fhZemhhclfjijWcZgdYcdgadgfhmbfdcgbefibYhlkdihlbcXdfdjggjhecfgffckdfhbdcbgaZefdakfjbWbchZYfZgYcge\
hgfjdgdegnfgdjfhehheehcfgibnkggacfjffnglmhXffgeblckgcffddgjhfeddificnklfXdfddfgdZfZnejcZddeekhgj\
hbjkgcmghkjhghfjcddeejlijhddgbdYbegbthejcVdejfchgffggegfeggfjZahedqkgjkpgffgcdghfcgiijgjfdZckffc\
hedjgdgffgdhcffbgjdhghhgkfikiegjmleYceidcggehbgdigdhjfgjigjjggjjgfefdgZefgghhejcuhkjkUgYbdgggggd\
ggehlgkggkkgggfgggfeggggcgfegrhghkgkifgdnhjfcgffhdfihjvgmlhWgdjfcggggchgggfhjdcXegigZhfedfeffgRd\
bdckjjggicggfjgfggfggggfjfefpghjgnenmlUekddZeZgYbdhdhjedgeZgghebfedjtgjffZfhgigghheiggigjgggfghh\
hfhggeeeigggbegiedhhgegiigecjiihadefddgffkdeggcdhggimhhmidifgieedffdefefeihdhfdjgihgeffYifghujlj\
jWeYghfgggggfgffbehhcccegbjhlkgrfmggUfdhcZgjfdbdiihfjhhfZfgeeXidgfqggjhtgoheaefheWhcdYnhngddgidc\
gljfhbYgdfkmggebpglfhmhhggfgfggegggmlimofeggiafffhZeelielfheilfghddgedfleicckeniYeaccjieficgfegf\
degfeiijeahgddfkjgiefgegfeelfdegbdahfjiifghgZimdcigejfejiiegggcgggdgieghjdcgdkgmnffnbidfengkihXg\
fjgghehejmkigdgkgdfigigghbfffhdgefghggghjhgdggfedighghhghgegfggZehjhllkmZbgddejiiglglhgbXigfcehf\
ffphgliegfdeaigjcjkdsodcedbekdgfdoiioZgmedcdaebcefjdkjhglXefggbggigXfpfiYgibdikfllrgjlkbgdfedegf\
cefekhdfcggnigqdYgdheejilhWbddYcikgeWddhglkhjeXbhegkiklhhgdggfgfigigfjgdgggfcdfgkfdegdbjhjdbhfki\
edddgdgiffZigifcggkedfedfbjekgghmgfficcdfgifddfhieejedhfjikfegheffidifaefdgdejeeigggiggfgfSfccer\
hojhiegigkdgiibdigebfhiemifgmcigeimghifciehefhiegkgfggthgiedhkhegifigmhifiefghfdefghZgfgebgijkcf\
fdgfggggnggghfggggfgddgfjgfgegeggogijgbeheffgfejdigfgojggidghggdggghigfieddfggjgggggggdhfilggggd\
jfffggeZdjifdgjggddfideikffdcfafdkihfbegigfheggdghfgfgeggfghhfbgijebfkggiegeifheihggiggggeggdggg\
icggggYgfhgkjgjfadgjicegifbggghjgghhfghggbeggdegggjpgfghgggggggggdfggggjggdggggggggghggggggagglf\
ahcfcZmekiddlggdfcbceiglgchhmgcggggggggjbjgggadddgfiffZbdfjgZmmkgcnrlnScfceXbaeXuwmzoYhgffXgffca\
idfgcgcfgffijgbgbefcfhgfbgifgennjmbfdacakfhaoolqgbgbhbZfelecghheffggichhhdcghgdYjhmeYgdeichafhUe\
iieeihnfaknilbdZebceeefongggdggfhdfgihdgcjiZdcheaefheihdfdgeihfaggbeehjjgghegjafeicmiimgbehegegg\
fhgdgggggggfjgfggegggfegehgcdeekZegehmkkfnZgfefghjfgfhfggachdfilpreffkfeehgehffijkegfggeggggZgie\
figemfhllijdigfeceegfpmglgdihhgcfgfecgggdjjjmghhdhcdglgibgekeoedmeYegfcgflihgifgghhgggafehdbghgf\
limlkeggdgfgegfmjgggegeghpgggfiggheigfgkbgggdmgfgkjgeikggghgijfjgcffifcggegcdkjecidgebgghgdfjkib\
fbfhmfklkadhecbgiigZggfbfcghcbehfhcghjeeggdighijggggggfggfiqghghehigffheejfifjejghgihhgggejgfgdg\
dighggggfgjjhggggecdgedkhighkliigfhjgemgeifiggdckjgggkgfiblgghhggffgdeghhnhgggcgegeqgehgfgfgingg\
gkjgifgSbdddsnsulZpmlddcebbVhkhdXfhjkqihtdYffeebbhfhapmodbnddbXccfiahhibadfmhqmhrhZckhfZfcfhjfmg\
gXhhifngglhbhfjfihhmdbihhgZgghfigfjkcgfhearolkYiiejigjghbggghuhhrkZfejgXjhggakiogdfffeYdbddekgjf\
kgdifbhfgieghggehdjgcekgdhihmeaefhfaifeinghkcZeeehxkomgYedfgkhehjfgihejikhecgfjgikejfYigiiYeihep\
ljhgadefhlhkocZhfhfnhhhkZhfdeZcghhqghnfbgjbdgfgfhijfjgVkedcnnrmmXbfbdjhldiZfgkaXjjhgaenlgkhhjgkj\
kljWcggWWfggebjhggZljfebfeccafjmhffmgffgfgeciefgbfhikcgffgYddkjYliabagefcagghelhfheakjdfZjfeeacc\
edfgjnfcfhmdbgdidhhcjgcfihhrhoggWjehesgehdbddlhqjhjdagffgejigbdheijffejeZgkfggggkhffhjeVgjehomnl\
heggghmggfevmlgkSebdefjifgejohdagiigfhjfgijhhhcighcggggfUeddbwfkmiVebfhhjifeXcfhcljggkqjjgfdcigd\
fgkefgggjfeggkfaddicXbdacrjiqgpfhigcihlfdghgeagghejjhggjggggiggffnhghhlgegehghhgbggghlgehhlhmjeX\
fahbeihgjbghjgfhfbibgikgmghgifgfgffjfldVgcacgghjgfejhgkjgggfggggkghggciggghgfifpejghlgigggggfgog\
gggfggggkgggigggggkggggefffeeghihrgeggwgikfckkegdefegdhkmgcffefpfgfggggggiggffsjfhgghggggggggejg\
dfegdgggghjkhgdggdehjegggggggggggggggihgijegggifgggjggggggggggggegg";
}
const PRIORS: bool = true;
const PRIOR_WEIGHT: f64 = 0.0;
fn main() {
let seed = seed_from_env_or_clock();
eprintln!("mcts: seed {seed}");
let mut rng = Rng::new(seed);
policy();
let mut mcts = Mcts::new(EXPLORATION, rng.next_u64());
mcts.priors = PRIORS;
mcts.prior_weight = PRIOR_WEIGHT;
let stdin = io::stdin();
let result = play(
&mut mcts,
&mut rng,
Input::new(stdin.lock()),
io::stdout().lock(),
&mut io::stderr(),
|start, limit| Budget::for_turn(start, limit, SHARE, RESERVE),
);
match result {
Ok(()) | Err(InputError::Eof) => {}
Err(err) => {
eprintln!("mcts: {err}");
std::process::exit(1);
}
}
}
fn play(
mcts: &mut Mcts<PatternBoard>,
rng: &mut Rng,
mut input: Input<impl BufRead>,
mut out: impl Write,
log: &mut impl Write,
budget: impl Fn(Instant, Duration) -> Budget,
) -> Result<(), InputError> {
let io_error = |err: io::Error| InputError::Io(err.to_string());
let mut board = Some(Board::new());
let mut actions = Vec::new();
let mut limit = FIRST_LIMIT;
loop {
let opponent: (i32, i32) = input.two()?;
let start = Instant::now();
let count: usize = input.one()?;
actions.clear();
for _ in 0..count {
actions.push(input.two::<i32, i32>()?);
}
if actions.is_empty() {
return Err(InputError::Parse {
line: count.to_string(),
expected: "at least one valid action".to_string(),
});
}
let tracked = board.is_some();
if opponent != (-1, -1) {
board = board.and_then(|position| apply(position, opponent));
}
let moves: Option<Vec<Move>> = actions.iter().map(|&action| to_move(action)).collect();
let position = match (board, moves) {
(Some(position), Some(moves)) if moves.iter().all(|&mv| position.is_legal(mv)) => {
Some((position, moves))
}
_ => None,
};
let choice = match position {
Some((position, moves)) => {
let mv = if moves.len() == 1 {
moves[0]
} else {
let root = PatternBoard {
board: position,
policy: policy(),
};
let result = mcts.search(&root, &moves, budget(start, limit));
let outlook = match result.proven {
Some(true) => "proven win".to_string(),
Some(false) => "proven loss".to_string(),
None => format!("expected score {:.3}", result.expected_score),
};
writeln!(
log,
"mcts: {} iterations, {} kept, {outlook}, {} ms",
result.iterations,
result.reused,
start.elapsed().as_millis()
)
.map_err(io_error)?;
result.best
};
board = Some(apply_move(position, mv));
actions[moves.iter().position(|&m| m == mv).expect("a candidate")]
}
None => {
if tracked {
writeln!(log, "mcts: lost track of the position; playing at random")
.map_err(io_error)?;
}
board = None;
*rng.pick(&actions).expect("the list is not empty")
}
};
writeln!(out, "{} {}", choice.0, choice.1)
.and_then(|()| out.flush())
.map_err(io_error)?;
limit = LIMIT;
}
}
fn to_move((row, col): (i32, i32)) -> Option<Move> {
Move::from_row_col(usize::try_from(row).ok()?, usize::try_from(col).ok()?)
}
fn apply(board: Board, action: (i32, i32)) -> Option<Board> {
let mv = to_move(action)?;
board.is_legal(mv).then(|| apply_move(board, mv))
}
fn apply_move(mut board: Board, mv: Move) -> Board {
board.play(mv);
board
}
#[allow(dead_code, unused_imports)]
mod cg_core {
pub mod input {
use std::fmt;
use std::io::BufRead;
use std::str::FromStr;
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum InputError {
Eof,
Io(String),
Parse { line: String, expected: String },
}
impl fmt::Display for InputError {
fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
match self {
InputError::Eof => write!(f, "input ended"),
InputError::Io(err) => write!(f, "cannot read input: {err}"),
InputError::Parse { line, expected } => {
write!(f, "expected {expected}, got {line:?}")
}
}
}
}
impl std::error::Error for InputError {}
pub struct Input<R> {
reader: R,
line: String,
}
impl<R: BufRead> Input<R> {
pub fn new(reader: R) -> Self {
Input {
reader,
line: String::new(),
}
}
pub fn line(&mut self) -> Result<&str, InputError> {
self.line.clear();
match self.reader.read_line(&mut self.line) {
Ok(0) => Err(InputError::Eof),
Ok(_) => Ok(self.line.trim_end_matches(['\n', '\r'])),
Err(err) => Err(InputError::Io(err.to_string())),
}
}
pub fn one<T: FromStr>(&mut self) -> Result<T, InputError> {
let line = self.line()?;
line.trim().parse().map_err(|_| parse_error::<T>(line, 1))
}
pub fn two<A: FromStr, B: FromStr>(&mut self) -> Result<(A, B), InputError> {
let line = self.line()?;
let mut parts = line.split_whitespace();
match (
parts.next().map(str::parse::<A>),
parts.next().map(str::parse::<B>),
parts.next(),
) {
(Some(Ok(a)), Some(Ok(b)), None) => Ok((a, b)),
_ => Err(InputError::Parse {
line: line.to_string(),
expected: format!(
"two values ({}, {})",
std::any::type_name::<A>(),
std::any::type_name::<B>()
),
}),
}
}
pub fn many<T: FromStr>(&mut self) -> Result<Vec<T>, InputError> {
let line = self.line()?;
line.split_whitespace()
.map(str::parse)
.collect::<Result<_, _>>()
.map_err(|_| parse_error::<T>(line, 0))
}
}
fn parse_error<T>(line: &str, count: usize) -> InputError {
let what = std::any::type_name::<T>();
InputError::Parse {
line: line.to_string(),
expected: match count {
1 => format!("one value ({what})"),
_ => format!("values ({what})"),
},
}
}
}
pub mod rng {
use std::time::{SystemTime, UNIX_EPOCH};
pub const SEED_ENV: &str = "CG_SEED";
pub fn seed_from_env_or_clock() -> u64 {
parse_seed(std::env::var(SEED_ENV).ok().as_deref()).unwrap_or_else(clock_seed)
}
fn parse_seed(value: Option<&str>) -> Option<u64> {
value?.trim().parse().ok()
}
fn clock_seed() -> u64 {
let nanos = SystemTime::now()
.duration_since(UNIX_EPOCH)
.map(|elapsed| elapsed.as_nanos() as u64)
.unwrap_or(0);
let local = 0u8;
let address = &local as *const u8 as u64;
nanos ^ address.rotate_left(32)
}
#[derive(Clone, Debug)]
pub struct Rng {
state: [u64; 4],
}
impl Rng {
pub fn new(seed: u64) -> Self {
let mut mix = seed;
Rng {
state: [
split_mix(&mut mix),
split_mix(&mut mix),
split_mix(&mut mix),
split_mix(&mut mix),
],
}
}
#[inline]
pub fn next_u64(&mut self) -> u64 {
let [s0, s1, s2, s3] = &mut self.state;
let result = s0.wrapping_add(*s3).rotate_left(23).wrapping_add(*s0);
let t = *s1 << 17;
*s2 ^= *s0;
*s3 ^= *s1;
*s1 ^= *s2;
*s0 ^= *s3;
*s2 ^= t;
*s3 = s3.rotate_left(45);
result
}
#[inline]
pub fn below(&mut self, n: u64) -> u64 {
assert!(n > 0, "Rng::below(0) has no possible value");
let mut product = u128::from(self.next_u64()) * u128::from(n);
if (product as u64) < n {
let threshold = n.wrapping_neg() % n;
while (product as u64) < threshold {
product = u128::from(self.next_u64()) * u128::from(n);
}
}
(product >> 64) as u64
}
pub fn unit(&mut self) -> f64 {
(self.next_u64() >> 11) as f64 * (1.0 / (1u64 << 53) as f64)
}
pub fn pick<'a, T>(&mut self, items: &'a [T]) -> Option<&'a T> {
if items.is_empty() {
None
} else {
items.get(self.below(items.len() as u64) as usize)
}
}
pub fn shuffle<T>(&mut self, items: &mut [T]) {
for i in (1..items.len()).rev() {
let j = self.below(i as u64 + 1) as usize;
items.swap(i, j);
}
}
}
fn split_mix(state: &mut u64) -> u64 {
*state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
let mut z = *state;
z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
z ^ (z >> 31)
}
}
pub mod time {
pub const TIME_SCALE_ENV: &str = "CG_TIME_SCALE";
pub fn time_scale() -> f64 {
parse_time_scale(std::env::var(TIME_SCALE_ENV).ok().as_deref())
}
fn parse_time_scale(value: Option<&str>) -> f64 {
value
.and_then(|text| text.trim().parse::<f64>().ok())
.filter(|scale| scale.is_finite() && *scale > 0.0)
.unwrap_or(1.0)
}
}
}
#[allow(dead_code, unused_imports)]
mod cg_search {
pub mod budget {
use std::time::{Duration, Instant};
use crate::cg_core::time::time_scale;
pub const FIXED_ITERATIONS_ENV: &str = "CG_FIXED_ITERS";
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Budget {
Until(Instant),
Iterations(u64),
}
impl Budget {
pub fn for_turn(
start: Instant,
limit: Duration,
share: f64,
reserve: Duration,
) -> Budget {
match fixed_iterations(std::env::var(FIXED_ITERATIONS_ENV).ok().as_deref()) {
Some(iterations) => Budget::Iterations(iterations),
None => Budget::Until(start + search_time(limit, time_scale(), share, reserve)),
}
}
#[inline]
pub fn is_spent(&self, iterations: u64) -> bool {
match *self {
Budget::Until(deadline) => Instant::now() >= deadline,
Budget::Iterations(limit) => iterations >= limit,
}
}
}
fn search_time(limit: Duration, scale: f64, share: f64, reserve: Duration) -> Duration {
limit.mul_f64(share).saturating_sub(reserve).mul_f64(scale)
}
fn fixed_iterations(value: Option<&str>) -> Option<u64> {
value?.trim().parse().ok().filter(|&n| n > 0)
}
}
pub mod game {
use crate::cg_core::rng::Rng;
pub trait Game: Clone + PartialEq {
type Move: Copy + PartialEq + std::fmt::Debug;
fn to_move(&self) -> usize;
fn legal_moves(&self, moves: &mut Vec<Self::Move>);
fn play(&mut self, mv: Self::Move);
fn score(&self) -> Option<f64>;
fn priors(&self, moves: &[Self::Move], weights: &mut Vec<f32>) {
let _ = moves;
weights.clear();
}
fn playout(&mut self, rng: &mut Rng) -> f64 {
let mut moves = Vec::new();
loop {
if let Some(score) = self.score() {
return score;
}
self.legal_moves(&mut moves);
let mv = *rng.pick(&moves).expect("a game that goes on has moves");
self.play(mv);
}
}
}
}
pub mod mcts {
use std::sync::OnceLock;
use crate::cg_core::rng::Rng;
use crate::cg_search::budget::Budget;
use crate::cg_search::game::Game;
const SQRT_LN_TABLE_LEN: usize = 1 << 16;
fn sqrt_ln_table() -> &'static [f64] {
static TABLE: OnceLock<Vec<f64>> = OnceLock::new();
TABLE.get_or_init(|| {
(0..SQRT_LN_TABLE_LEN as u32)
.map(|n| f64::from(n.max(1)).ln().sqrt())
.collect()
})
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Proof {
Unknown,
MoverWins,
MoverLoses,
}
#[derive(Clone, Copy, Debug)]
struct Node<M> {
mv: M,
mover: u8,
proof: Proof,
expanded: bool,
first_child: u32,
children: u32,
visits: u32,
value: f32,
inv_sqrt_visits: f32,
prior: f32,
bias: f32,
}
#[derive(Clone, Debug, PartialEq)]
pub struct SearchResult<M> {
pub best: M,
pub iterations: u64,
pub reused: u64,
pub proven: Option<bool>,
pub expected_score: f64,
pub nodes: usize,
}
pub struct Mcts<G: Game> {
pub exploration: f64,
pub priors: bool,
pub prior_weight: f64,
rng: Rng,
nodes: Vec<Node<G::Move>>,
root: Option<G>,
spare: Vec<Node<G::Move>>,
origin: Vec<u32>,
moves: Vec<G::Move>,
weights: Vec<f32>,
ranked: Vec<(f32, G::Move)>,
path: Vec<u32>,
sqrt_ln: &'static [f64],
}
impl<G: Game> Mcts<G> {
pub fn new(exploration: f64, seed: u64) -> Self {
Mcts {
exploration,
priors: false,
prior_weight: 0.0,
rng: Rng::new(seed),
nodes: Vec::new(),
root: None,
spare: Vec::new(),
origin: Vec::new(),
moves: Vec::new(),
weights: Vec::new(),
ranked: Vec::new(),
path: Vec::new(),
sqrt_ln: sqrt_ln_table(),
}
}
pub fn search(
&mut self,
root: &G,
candidates: &[G::Move],
budget: Budget,
) -> SearchResult<G::Move> {
assert!(!candidates.is_empty(), "nothing to choose from");
assert!(root.score().is_none(), "the game is over");
let win = if root.to_move() == 0 { 1.0 } else { 0.0 };
for &mv in candidates {
let mut next = root.clone();
next.play(mv);
if next.score() == Some(win) {
return SearchResult {
best: mv,
iterations: 0,
reused: 0,
proven: Some(true),
expected_score: 1.0,
nodes: self.nodes.len(),
};
}
}
if !self.reuse(root, candidates) {
self.start(root, candidates);
}
self.root = Some(root.clone());
let reused = u64::from(self.nodes[0].visits);
let mut iterations = 0;
while self.nodes[0].proof == Proof::Unknown
&& ((iterations as usize) < candidates.len() || !budget.is_spent(iterations))
{
self.iterate(root);
iterations += 1;
}
let children = || self.children(0).map(|index| &self.nodes[index]);
let best = children()
.find(|child| child.proof == Proof::MoverWins)
.or_else(|| {
children()
.filter(|child| child.proof != Proof::MoverLoses)
.max_by_key(|child| child.visits)
})
.or_else(|| children().max_by_key(|child| child.visits))
.expect("the root has children");
let proven = match self.nodes[0].proof {
Proof::Unknown => None,
Proof::MoverWins => Some(false),
Proof::MoverLoses => Some(true),
};
let expected_score = match best.proof {
Proof::MoverWins => 1.0,
Proof::MoverLoses => 0.0,
Proof::Unknown => f64::from(best.value),
};
SearchResult {
best: best.mv,
iterations,
reused,
proven,
expected_score,
nodes: self.nodes.len(),
}
}
pub fn root_visits(&self) -> impl Iterator<Item = (G::Move, u32)> + '_ {
let children = if self.nodes.is_empty() {
0..0
} else {
self.children(0)
};
children.map(|index| (self.nodes[index].mv, self.nodes[index].visits))
}
fn start(&mut self, root: &G, candidates: &[G::Move]) {
self.nodes.clear();
self.nodes.push(Node {
mv: candidates[0],
mover: (1 - root.to_move()) as u8,
proof: Proof::Unknown,
expanded: false,
first_child: 0,
children: 0,
visits: 0,
value: 0.0,
inv_sqrt_visits: 0.0,
prior: 0.0,
bias: 0.0,
});
self.moves.clear();
self.moves.extend_from_slice(candidates);
self.expand(0, root);
}
fn reuse(&mut self, root: &G, candidates: &[G::Move]) -> bool {
let Some(node) = self.find(root) else {
return false;
};
let kept = &self.nodes[node];
let same_moves = kept.expanded
&& kept.children as usize == candidates.len()
&& self
.children(node)
.all(|child| candidates.contains(&self.nodes[child].mv));
if !same_moves {
return false;
}
if node != 0 {
self.keep_subtree(node);
}
true
}
fn find(&self, position: &G) -> Option<usize> {
let previous = self.root.as_ref()?;
if previous == position {
return Some(0);
}
for child in self.children(0) {
let mut after_one = previous.clone();
after_one.play(self.nodes[child].mv);
if &after_one == position {
return Some(child);
}
for grandchild in self.children(child) {
let mut after_two = after_one.clone();
after_two.play(self.nodes[grandchild].mv);
if &after_two == position {
return Some(grandchild);
}
}
}
None
}
fn keep_subtree(&mut self, node: usize) {
let capacity = self.nodes.capacity();
if self.spare.capacity() < capacity {
self.spare = Vec::with_capacity(capacity);
}
if self.origin.capacity() < capacity {
self.origin = Vec::with_capacity(capacity);
}
self.spare.clear();
self.origin.clear();
self.spare.push(self.nodes[node]);
self.origin.push(node as u32);
let mut next = 0;
while next < self.spare.len() {
let old = self.nodes[self.origin[next] as usize];
if old.expanded {
self.spare[next].first_child = self.spare.len() as u32;
for child in old.first_child..old.first_child + old.children {
self.spare.push(self.nodes[child as usize]);
self.origin.push(child);
}
}
next += 1;
}
std::mem::swap(&mut self.nodes, &mut self.spare);
}
fn children(&self, node: usize) -> std::ops::Range<usize> {
let node = &self.nodes[node];
let first = node.first_child as usize;
first
..first
+ if node.expanded {
node.children as usize
} else {
0
}
}
fn iterate(&mut self, root: &G) {
let mut state = root.clone();
let mut node = 0;
let mut proved = false;
self.path.clear();
self.path.push(0);
let score = loop {
let current = self.nodes[node];
let mover_score = |wins: bool| {
if wins == (current.mover == 0) {
1.0
} else {
0.0
}
};
match current.proof {
Proof::MoverWins => break mover_score(true),
Proof::MoverLoses => break mover_score(false),
Proof::Unknown => {}
}
if let Some(score) = state.score() {
if node != 0 && score != 0.5 {
let wins = score == mover_score(true);
self.nodes[node].proof = if wins {
Proof::MoverWins
} else {
Proof::MoverLoses
};
proved = true;
}
break score;
}
if !current.expanded {
if self.nodes[node].visits == 0 {
break state.playout(&mut self.rng);
}
state.legal_moves(&mut self.moves);
self.expand(node, &state);
}
node = self.select(node);
state.play(self.nodes[node].mv);
self.path.push(node as u32);
};
let prior_weight = self.prior_weight as f32;
for &index in &self.path {
let node = &mut self.nodes[index as usize];
node.visits += 1;
let mover_score = if node.mover == 0 { score } else { 1.0 - score };
let visits = node.visits as f32;
node.value += (mover_score as f32 - node.value) / visits;
node.inv_sqrt_visits = visits.sqrt().recip();
node.bias = prior_weight * node.prior / (visits + 1.0);
}
if proved {
self.prove_ancestors();
}
}
fn prove_ancestors(&mut self) {
for depth in (0..self.path.len() - 1).rev() {
let node = self.path[depth] as usize;
let mut all_lost = true;
let mut proof = Proof::Unknown;
for child in self.children(node) {
match self.nodes[child].proof {
Proof::MoverWins => {
proof = Proof::MoverLoses;
break;
}
Proof::MoverLoses => {}
Proof::Unknown => all_lost = false,
}
}
if proof == Proof::Unknown && all_lost {
proof = Proof::MoverWins;
}
if proof == Proof::Unknown {
return;
}
self.nodes[node].proof = proof;
}
}
fn expand(&mut self, node: usize, state: &G) {
self.rng.shuffle(&mut self.moves);
let count = self.moves.len();
self.weights.clear();
if self.priors {
state.priors(&self.moves, &mut self.weights);
}
let total: f32 = self.weights.iter().sum();
self.ranked.clear();
if self.weights.len() == count && total > 0.0 {
self.ranked.extend(
self.weights
.iter()
.zip(&self.moves)
.map(|(&weight, &mv)| (weight / total, mv)),
);
self.ranked.sort_unstable_by(|a, b| b.0.total_cmp(&a.0));
} else {
self.ranked.extend(self.moves.iter().map(|&mv| (0.0, mv)));
}
let to_move = state.to_move() as u8;
let prior_weight = self.prior_weight as f32;
let first_child = self.nodes.len() as u32;
for &(prior, mv) in &self.ranked {
self.nodes.push(Node {
mv,
mover: to_move,
proof: Proof::Unknown,
expanded: false,
first_child: 0,
children: 0,
visits: 0,
value: 0.0,
inv_sqrt_visits: 0.0,
prior,
bias: prior_weight * prior,
});
}
let parent = &mut self.nodes[node];
parent.expanded = true;
parent.first_child = first_child;
parent.children = count as u32;
}
fn select(&self, node: usize) -> usize {
let parent = &self.nodes[node];
let first = parent.first_child as usize;
let children = &self.nodes[first..first + parent.children as usize];
let visits = parent.visits.max(1);
let sqrt_ln = match self.sqrt_ln.get(visits as usize) {
Some(&value) => value,
None => f64::from(visits).ln().sqrt(),
};
let spread = (self.exploration * sqrt_ln) as f32;
let mut best = 0;
let mut best_bound = f32::NEG_INFINITY;
for (offset, child) in children.iter().enumerate() {
match child.proof {
Proof::MoverLoses => continue,
Proof::MoverWins => return first + offset,
Proof::Unknown => {}
}
if child.visits == 0 {
return first + offset;
}
let bound = child.value + spread * child.inv_sqrt_visits + child.bias;
if bound > best_bound {
best_bound = bound;
best = offset;
}
}
first + best
}
}
}
pub use budget::Budget;
pub use game::Game;
pub use mcts::{Mcts, SearchResult};
}
#[allow(dead_code, unused_imports)]
mod uttt_engine {
pub mod board {
use crate::cg_core::rng::Rng;
use crate::uttt_engine::grid::{self, FULL};
use crate::uttt_engine::moves::{Move, MoveList};
mod patterns {
use std::sync::OnceLock;
use crate::cg_core::rng::Rng;
use super::{Board, Status, ANY_BOARD};
use crate::uttt_engine::grid::{self, FULL};
use crate::uttt_engine::moves::Move;
pub const DESTINATIONS: usize = 5;
pub const PATTERNS: usize = 19_683;
pub const PATTERN_CELLS: usize = 5_255;
pub const PATTERN_FEATURES: usize = PATTERN_CELLS * DESTINATIONS;
const ALPHABET: &[u8; 64] =
b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
const B3: [u16; 512] = {
let mut table = [0u16; 512];
let mut mask = 0;
while mask < 512 {
let (mut value, mut power, mut cell) = (0u16, 1u16, 0);
while cell < 9 {
if mask & (1 << cell) != 0 {
value += power;
}
power *= 3;
cell += 1;
}
table[mask] = value;
mask += 1;
}
table
};
pub fn symmetric_cell(symmetry: usize, cell: usize) -> usize {
let (row, col) = (cell / 3, cell % 3);
let (row, col) = match symmetry {
0 => (row, col),
1 => (col, 2 - row),
2 => (2 - row, 2 - col),
3 => (2 - col, row),
4 => (row, 2 - col),
5 => (2 - row, col),
6 => (col, row),
_ => (2 - col, 2 - row),
};
3 * row + col
}
fn pattern_ids() -> &'static [u16] {
static IDS: OnceLock<Vec<u16>> = OnceLock::new();
IDS.get_or_init(|| {
let mut ids = vec![0u16; PATTERNS * 9];
let mut count = 0usize;
for pattern in 0..PATTERNS {
let mut digits = [0usize; 9];
let mut rest = pattern;
for digit in &mut digits {
*digit = rest % 3;
rest /= 3;
}
let mask = |state: usize| {
(0..9)
.filter(|&cell| digits[cell] == state)
.fold(0u16, |mask, cell| mask | 1 << cell)
};
let (empty, mine, theirs) = (mask(0), mask(1), mask(2));
if empty == 0 || grid::has_line(mine) || grid::has_line(theirs) {
continue;
}
let images: [usize; 8] = std::array::from_fn(|symmetry| {
(0..9)
.map(|cell| {
digits[cell] * 3usize.pow(symmetric_cell(symmetry, cell) as u32)
})
.sum()
});
for cell in grid::cells(empty) {
let canonical = (0..8)
.map(|symmetry| (images[symmetry], symmetric_cell(symmetry, cell)))
.min()
.expect("eight symmetries");
ids[9 * pattern + cell] = if canonical == (pattern, cell) {
count += 1;
(count - 1) as u16
} else {
ids[9 * canonical.0 + canonical.1]
};
}
}
assert_eq!(count, PATTERN_CELLS, "canonical pattern cells");
ids
})
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PatternPolicy {
weights: Vec<u32>,
plies: u32,
}
impl PatternPolicy {
pub fn from_log_weights(log_weights: &[f32]) -> Result<Self, String> {
if log_weights.len() != PATTERN_FEATURES {
return Err(format!(
"{} weights instead of {PATTERN_FEATURES}",
log_weights.len()
));
}
let weights = log_weights
.iter()
.map(|&log| {
let scaled = f64::from(log.clamp(-8.0, 7.75) - 7.75).exp()
* f64::from(1u32 << 24);
(scaled.round() as u32).clamp(1, (1 << 24) - 1)
})
.collect();
Ok(PatternPolicy {
weights,
plies: u32::MAX,
})
}
pub fn decode(text: &str) -> Result<Self, String> {
let log_weights = text
.bytes()
.map(|byte| {
ALPHABET
.iter()
.position(|&digit| digit == byte)
.map(|q| (q as f32 - 32.0) / 4.0)
.ok_or_else(|| format!("{:?} is not a weight", char::from(byte)))
})
.collect::<Result<Vec<f32>, String>>()?;
Self::from_log_weights(&log_weights)
}
pub fn for_plies(mut self, plies: u32) -> Self {
self.plies = plies;
self
}
}
pub fn encode_pattern_weights(log_weights: &[f32]) -> String {
log_weights
.iter()
.map(|&log| {
let q = ((log * 4.0).round() + 32.0).clamp(0.0, 63.0) as usize;
char::from(ALPHABET[q])
})
.collect()
}
impl Board {
#[inline(always)]
fn pattern(&self, board: usize) -> usize {
let seat = self.to_move();
usize::from(B3[usize::from(self.marks[seat][board])])
+ 2 * usize::from(B3[usize::from(self.marks[1 - seat][board])])
}
#[inline(always)]
fn destinations(&self, board: usize) -> [usize; 9] {
let seat = self.to_move();
let free = self.board_features(board).free;
let (theirs, mine) = (self.threats[1 - seat], self.threats[seat]);
std::array::from_fn(|cell| {
let bit = |mask: u16| usize::from((mask >> cell) & 1);
(1 + bit(theirs) + 2 * bit(mine)) * (1 - bit(free))
})
}
pub fn pattern_feature(&self, mv: Move) -> usize {
debug_assert!(self.is_legal(mv), "illegal move {mv}");
let (board, cell) = (mv.board(), mv.cell());
let id = pattern_ids()[9 * self.pattern(board) + cell];
usize::from(id) * DESTINATIONS + self.destinations(board)[cell]
}
pub fn pattern_move_weights(
&self,
policy: &PatternPolicy,
moves: &[Move],
weights: &mut Vec<f32>,
) {
weights.clear();
weights.extend(
moves
.iter()
.map(|&mv| policy.weights[self.pattern_feature(mv)] as f32),
);
}
#[inline(always)]
fn pattern_cumulative(
&self,
board: usize,
ids: &[u16],
policy: &PatternPolicy,
) -> [u32; 9] {
let empty = self.empty_cells(board);
let destinations = self.destinations(board);
let row = &ids[9 * self.pattern(board)..][..9];
let mut cumulative = [0u32; 9];
let mut total = 0;
for (cell, ((sum, &id), &destination)) in cumulative
.iter_mut()
.zip(row)
.zip(&destinations)
.enumerate()
{
let feature = usize::from(id) * DESTINATIONS + destination;
total += policy.weights[feature] * u32::from((empty >> cell) & 1);
*sum = total;
}
cumulative
}
#[inline(always)]
fn pattern_cell(
&self,
policy: &PatternPolicy,
ids: &[u16],
rng: &mut Rng,
) -> (usize, usize) {
if let Some(winning) = self.game_winning_cell() {
return winning;
}
if self.target != ANY_BOARD {
let board = usize::from(self.target);
let cumulative = self.pattern_cumulative(board, ids, policy);
let pick = rng.below(u64::from(cumulative[8])) as u32;
return (board, Board::cell_at(&cumulative, pick));
}
let mut boards = [[0u32; 9]; 9];
let mut totals = [0u32; 9];
let mut total = 0;
for board in grid::cells(!self.closed & FULL) {
boards[board] = self.pattern_cumulative(board, ids, policy);
total += boards[board][8];
totals[board] = total;
}
let pick = rng.below(u64::from(total)) as u32;
for board in grid::cells(!self.closed & FULL) {
if pick < totals[board] {
let before = totals[board] - boards[board][8];
return (board, Board::cell_at(&boards[board], pick - before));
}
}
unreachable!("the draw is below the total weight")
}
pub fn pattern_move(&self, policy: &PatternPolicy, rng: &mut Rng) -> Move {
let (board, cell) = self.pattern_cell(policy, pattern_ids(), rng);
Move::new(board, cell)
}
pub fn pattern_playout(&mut self, policy: &PatternPolicy, rng: &mut Rng) -> Status {
let ids = pattern_ids();
let mut plies = 0;
while self.status == Status::Ongoing && plies < policy.plies {
let (board, cell) = self.pattern_cell(policy, ids, rng);
self.play_at(board, cell);
plies += 1;
}
self.decisive_playout(rng)
}
}
}
mod policy {
use crate::cg_core::rng::Rng;
use super::{Board, Status, ANY_BOARD};
use crate::uttt_engine::grid::{self, FULL};
use crate::uttt_engine::moves::Move;
pub const WINS_BOARD: u8 = 1;
pub const BLOCKS: u8 = 2;
pub const GIVES_FREE_CHOICE: u8 = 4;
pub const GIVES_BOARD: u8 = 8;
pub const CENTRE: u8 = 16;
pub const FEATURES: usize = 5;
pub const CLASSES: usize = 1 << FEATURES;
pub const FEATURE_NAMES: [&str; FEATURES] = [
"wins board",
"blocks",
"gives free choice",
"gives board",
"centre",
];
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PlayoutPolicy {
weights: [u32; CLASSES],
plies: u32,
}
impl PlayoutPolicy {
pub const fn new(weights: [u32; CLASSES]) -> Self {
let mut class = 0;
while class < CLASSES {
assert!(weights[class] < 1 << 20, "weights must stay below 2^20");
class += 1;
}
PlayoutPolicy {
weights,
plies: u32::MAX,
}
}
pub const fn for_plies(self, plies: u32) -> Self {
PlayoutPolicy {
weights: self.weights,
plies,
}
}
pub fn uniform() -> Self {
PlayoutPolicy::new([1; CLASSES])
}
pub fn weights(&self) -> &[u32; CLASSES] {
&self.weights
}
}
#[derive(Clone, Copy)]
pub(super) struct BoardFeatures {
empty: u16,
wins: u16,
blocks: u16,
pub(super) free: u16,
}
impl Board {
#[inline(always)]
pub(super) fn board_features(&self, board: usize) -> BoardFeatures {
let seat = self.to_move();
let empty = self.empty_cells(board);
let wins = grid::completing_cells(self.marks[seat][board]) & empty;
let blocks = grid::completing_cells(self.marks[1 - seat][board]) & empty;
let mut closing = wins;
if grid::count(empty) == 1 {
closing |= empty;
}
let free = (self.closed | (closing & (1 << board))) & empty;
BoardFeatures {
empty,
wins,
blocks,
free,
}
}
#[inline(always)]
fn cell_class(features: &BoardFeatures, threats: u16, cell: usize) -> usize {
let has = |mask: u16| usize::from((mask >> cell) & 1);
has(features.wins)
| has(features.blocks) << 1
| has(features.free) << 2
| has(threats & !features.free) << 3
| usize::from(cell == 4) << 4
}
pub fn move_class(&self, mv: Move) -> usize {
debug_assert!(self.is_legal(mv), "illegal move {mv}");
let features = self.board_features(mv.board());
Board::cell_class(&features, self.threats[1 - self.to_move()], mv.cell())
}
pub fn move_weights(
&self,
policy: &PlayoutPolicy,
moves: &[Move],
weights: &mut Vec<f32>,
) {
let threats = self.threats[1 - self.to_move()];
let mut features: [Option<BoardFeatures>; 9] = [None; 9];
weights.clear();
for &mv in moves {
debug_assert!(self.is_legal(mv), "illegal move {mv}");
let board = mv.board();
let board_features =
*features[board].get_or_insert_with(|| self.board_features(board));
let class = Board::cell_class(&board_features, threats, mv.cell());
weights.push(policy.weights[class] as f32);
}
}
pub fn policy_move(&self, policy: &PlayoutPolicy, rng: &mut Rng) -> Move {
let (board, cell) = self.policy_cell(policy, rng);
Move::new_unchecked(board, cell)
}
#[inline(always)]
fn cumulative_weights(
&self,
board: usize,
threats: u16,
policy: &PlayoutPolicy,
) -> [u32; 9] {
let features = self.board_features(board);
let mut cumulative = [0u32; 9];
let mut total = 0;
for (cell, sum) in cumulative.iter_mut().enumerate() {
let class = Board::cell_class(&features, threats, cell);
let weight = policy.weights[class & (CLASSES - 1)];
total += weight * u32::from((features.empty >> cell) & 1);
*sum = total;
}
cumulative
}
#[inline(always)]
pub(super) fn cell_at(cumulative: &[u32; 9], pick: u32) -> usize {
cumulative.iter().map(|&sum| usize::from(sum <= pick)).sum()
}
#[inline(always)]
fn policy_cell(&self, policy: &PlayoutPolicy, rng: &mut Rng) -> (usize, usize) {
if let Some(winning) = self.game_winning_cell() {
return winning;
}
let threats = self.threats[1 - self.to_move()];
if self.target != ANY_BOARD {
let board = usize::from(self.target);
let cumulative = self.cumulative_weights(board, threats, policy);
let total = cumulative[8];
if total == 0 {
return self.random_cell(rng);
}
let pick = rng.below(u64::from(total)) as u32;
return (board, Board::cell_at(&cumulative, pick));
}
let mut boards = [[0u32; 9]; 9];
let mut totals = [0u32; 9];
let mut total = 0;
for board in grid::cells(!self.closed & FULL) {
boards[board] = self.cumulative_weights(board, threats, policy);
total += boards[board][8];
totals[board] = total;
}
if total == 0 {
return self.random_cell(rng);
}
let pick = rng.below(u64::from(total)) as u32;
for board in grid::cells(!self.closed & FULL) {
if pick < totals[board] {
let before = totals[board] - boards[board][8];
return (board, Board::cell_at(&boards[board], pick - before));
}
}
unreachable!("the draw is below the total weight")
}
pub fn policy_playout(&mut self, policy: &PlayoutPolicy, rng: &mut Rng) -> Status {
let mut plies = 0;
while self.status == Status::Ongoing && plies < policy.plies {
let (board, cell) = self.policy_cell(policy, rng);
self.play_at(board, cell);
plies += 1;
}
self.decisive_playout(rng)
}
}
}
pub use patterns::{
encode_pattern_weights, symmetric_cell, PatternPolicy, DESTINATIONS, PATTERNS,
PATTERN_CELLS, PATTERN_FEATURES,
};
pub use policy::{
PlayoutPolicy, BLOCKS, CENTRE, CLASSES, FEATURES, FEATURE_NAMES, GIVES_BOARD,
GIVES_FREE_CHOICE, WINS_BOARD,
};
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Status {
Ongoing,
Win(usize),
Draw,
}
const ANY_BOARD: u8 = 9;
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Board {
marks: [[u16; 9]; 2],
won: [u16; 2],
closed: u16,
threats: [u16; 2],
target: u8,
to_move: u8,
status: Status,
}
impl Default for Board {
fn default() -> Self {
Board::new()
}
}
impl Board {
pub fn new() -> Self {
Board {
marks: [[0; 9]; 2],
won: [0; 2],
closed: 0,
threats: [0; 2],
target: ANY_BOARD,
to_move: 0,
status: Status::Ongoing,
}
}
#[inline]
pub fn to_move(&self) -> usize {
usize::from(self.to_move)
}
#[inline]
pub fn status(&self) -> Status {
self.status
}
pub fn mark(&self, mv: Move) -> Option<usize> {
let bit = 1 << mv.cell();
(0..2).find(|&seat| self.marks[seat][mv.board()] & bit != 0)
}
pub fn small_winner(&self, board: usize) -> Option<usize> {
(0..2).find(|&seat| self.won[seat] & (1 << board) != 0)
}
pub fn points(&self) -> [u32; 2] {
[self.won[0].count_ones(), self.won[1].count_ones()]
}
pub fn target(&self) -> Option<usize> {
(self.target != ANY_BOARD).then_some(usize::from(self.target))
}
pub fn is_closed(&self, board: usize) -> bool {
self.closed & (1 << board) != 0
}
#[inline]
pub fn cells(&self, seat: usize, board: usize) -> u16 {
self.marks[seat][board]
}
#[inline]
pub fn won_boards(&self, seat: usize) -> u16 {
self.won[seat]
}
#[inline]
pub fn closed_boards(&self) -> u16 {
self.closed
}
#[inline]
pub fn threat_boards(&self, seat: usize) -> u16 {
self.threats[seat]
}
#[inline]
fn empty_cells(&self, board: usize) -> u16 {
!(self.marks[0][board] | self.marks[1][board]) & FULL
}
pub fn is_legal(&self, mv: Move) -> bool {
let board = mv.board();
self.status == Status::Ongoing
&& !self.is_closed(board)
&& (self.target == ANY_BOARD || usize::from(self.target) == board)
&& self.empty_cells(board) & (1 << mv.cell()) != 0
}
pub fn legal_moves(&self, moves: &mut MoveList) {
moves.clear();
if self.status != Status::Ongoing {
return;
}
if self.target != ANY_BOARD {
self.push_board_moves(usize::from(self.target), moves);
} else {
for board in grid::cells(!self.closed & FULL) {
self.push_board_moves(board, moves);
}
}
}
#[inline]
fn push_board_moves(&self, board: usize, moves: &mut MoveList) {
for cell in grid::cells(self.empty_cells(board)) {
moves.push(Move::new(board, cell));
}
}
#[inline(always)]
pub fn play(&mut self, mv: Move) {
debug_assert!(self.is_legal(mv), "illegal move {mv} in {self:?}");
self.play_at(mv.board(), mv.cell());
}
#[inline(always)]
fn play_at(&mut self, board: usize, cell: usize) {
let seat = usize::from(self.to_move);
let marks = self.marks[seat][board] | (1 << cell);
self.marks[seat][board] = marks;
if grid::has_line(marks) {
self.won[seat] |= 1 << board;
self.closed |= 1 << board;
if grid::has_line(self.won[seat]) {
self.status = Status::Win(seat);
} else if self.closed == FULL {
self.status = self.status_on_points();
}
} else if marks | self.marks[1 - seat][board] == FULL {
self.closed |= 1 << board;
if self.closed == FULL {
self.status = self.status_on_points();
}
}
let bit = 1 << board;
let open = self.closed & bit == 0;
let other = self.marks[1 - seat][board];
let empty = !(marks | other) & FULL;
let mine = open && grid::completing_cells(marks) & empty != 0;
let theirs = open && grid::completing_cells(other) & empty != 0;
self.threats[seat] = (self.threats[seat] & !bit) | (u16::from(mine) << board);
self.threats[1 - seat] =
(self.threats[1 - seat] & !bit) | (u16::from(theirs) << board);
self.target = if self.is_closed(cell) {
ANY_BOARD
} else {
cell as u8
};
self.to_move ^= 1;
}
fn status_on_points(&self) -> Status {
let [zero, one] = self.points();
match zero.cmp(&one) {
std::cmp::Ordering::Greater => Status::Win(0),
std::cmp::Ordering::Less => Status::Win(1),
std::cmp::Ordering::Equal => Status::Draw,
}
}
#[inline(always)]
pub fn random_move(&self, rng: &mut Rng) -> Move {
let (board, cell) = self.random_cell(rng);
Move::new_unchecked(board, cell)
}
#[inline(always)]
fn random_cell(&self, rng: &mut Rng) -> (usize, usize) {
debug_assert_eq!(self.status, Status::Ongoing);
if self.target != ANY_BOARD {
let board = usize::from(self.target);
let empty = self.empty_cells(board);
let index = rng.below(u64::from(grid::count(empty))) as u32;
return (board, grid::nth_cell(empty, index));
}
let open = !self.closed & FULL;
let total: u32 = grid::cells(open)
.map(|board| grid::count(self.empty_cells(board)))
.sum();
let mut index = rng.below(u64::from(total)) as u32;
for board in grid::cells(open) {
let empty = self.empty_cells(board);
let count = grid::count(empty);
if index < count {
return (board, grid::nth_cell(empty, index));
}
index -= count;
}
unreachable!("a game that goes on has a legal move")
}
pub fn random_playout(&mut self, rng: &mut Rng) -> Status {
while self.status == Status::Ongoing {
let (board, cell) = self.random_cell(rng);
self.play_at(board, cell);
}
self.status
}
#[inline]
fn game_winning_boards(&self, seat: usize, boards: u16) -> u16 {
grid::completing_cells(self.won[seat]) & boards & self.threats[seat]
}
#[inline]
pub fn decisive_move(&self, rng: &mut Rng) -> Move {
let (board, cell) = self.decisive_cell(rng);
Move::new_unchecked(board, cell)
}
#[inline(always)]
fn decisive_cell(&self, rng: &mut Rng) -> (usize, usize) {
match self.game_winning_cell() {
Some(winning) => winning,
None => self.random_cell(rng),
}
}
pub fn game_winning_move(&self) -> Option<Move> {
self.game_winning_cell()
.map(|(board, cell)| Move::new_unchecked(board, cell))
}
#[inline(always)]
fn game_winning_cell(&self) -> Option<(usize, usize)> {
let seat = self.to_move();
let allowed = if self.target == ANY_BOARD {
FULL
} else {
1 << self.target
};
let winning = self.game_winning_boards(seat, allowed);
if winning == 0 {
return None;
}
let board = winning.trailing_zeros() as usize;
let cells =
grid::completing_cells(self.marks[seat][board]) & self.empty_cells(board);
Some((board, cells.trailing_zeros() as usize))
}
pub fn decisive_playout(&mut self, rng: &mut Rng) -> Status {
while self.status == Status::Ongoing {
let (board, cell) = self.decisive_cell(rng);
self.play_at(board, cell);
}
self.status
}
}
}
pub mod grid {
pub const FULL: u16 = 0x1FF;
pub const LINES: [u16; 8] = [
0b000_000_111,
0b000_111_000,
0b111_000_000,
0b001_001_001,
0b010_010_010,
0b100_100_100,
0b100_010_001,
0b001_010_100,
];
const fn line_table() -> [bool; 512] {
let mut table = [false; 512];
let mut mask = 0;
while mask < 512 {
let mut line = 0;
while line < LINES.len() {
if mask as u16 & LINES[line] == LINES[line] {
table[mask] = true;
}
line += 1;
}
mask += 1;
}
table
}
static HAS_LINE: [bool; 512] = line_table();
#[inline]
pub fn has_line(mask: u16) -> bool {
HAS_LINE[usize::from(mask & FULL)]
}
const fn completing_table() -> [u16; 512] {
let table = line_table();
let mut completing = [0; 512];
let mut mask = 0;
while mask < 512 {
let mut cell = 0;
while cell < 9 {
let with = mask | (1 << cell);
if with != mask && table[with] {
completing[mask] |= 1 << cell;
}
cell += 1;
}
mask += 1;
}
completing
}
static COMPLETING: [u16; 512] = completing_table();
#[inline]
pub fn completing_cells(mask: u16) -> u16 {
COMPLETING[usize::from(mask & FULL)]
}
const fn cell_tables() -> ([u8; 512], [[u8; 9]; 512]) {
let mut counts = [0; 512];
let mut nth = [[0; 9]; 512];
let mut mask = 0;
while mask < 512 {
let mut cell = 0;
while cell < 9 {
if mask & (1 << cell) != 0 {
nth[mask][counts[mask] as usize] = cell as u8;
counts[mask] += 1;
}
cell += 1;
}
mask += 1;
}
(counts, nth)
}
static CELL_TABLES: ([u8; 512], [[u8; 9]; 512]) = cell_tables();
#[inline]
pub fn count(mask: u16) -> u32 {
u32::from(CELL_TABLES.0[usize::from(mask & FULL)])
}
#[inline]
pub fn nth_cell(mask: u16, n: u32) -> usize {
debug_assert!(n < count(mask), "fewer than {} cells", n + 1);
usize::from(CELL_TABLES.1[usize::from(mask & FULL)][n as usize])
}
#[inline]
pub fn cells(mut mask: u16) -> impl Iterator<Item = usize> {
std::iter::from_fn(move || {
if mask == 0 {
None
} else {
let cell = mask.trailing_zeros() as usize;
mask &= mask - 1;
Some(cell)
}
})
}
}
pub mod moves {
use std::fmt;
use std::ops::Deref;
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Move(u8);
impl Move {
pub fn new(board: usize, cell: usize) -> Move {
assert!(board < 9 && cell < 9, "no cell {cell} in board {board}");
Move((9 * board + cell) as u8)
}
#[inline]
pub(crate) fn new_unchecked(board: usize, cell: usize) -> Move {
debug_assert!(board < 9 && cell < 9, "no cell {cell} in board {board}");
Move((9 * board + cell) as u8)
}
pub fn from_row_col(row: usize, col: usize) -> Option<Move> {
(row < 9 && col < 9)
.then(|| Move::new(3 * (row / 3) + col / 3, 3 * (row % 3) + col % 3))
}
#[inline]
pub fn board(self) -> usize {
usize::from(self.0 / 9)
}
#[inline]
pub fn cell(self) -> usize {
usize::from(self.0 % 9)
}
pub fn row_col(self) -> (usize, usize) {
let (board, cell) = (self.board(), self.cell());
(3 * (board / 3) + cell / 3, 3 * (board % 3) + cell % 3)
}
}
impl fmt::Display for Move {
fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
let (row, col) = self.row_col();
write!(f, "{row} {col}")
}
}
#[derive(Clone)]
pub struct MoveList {
moves: [Move; 81],
len: usize,
}
impl MoveList {
pub fn new() -> Self {
MoveList {
moves: [Move(0); 81],
len: 0,
}
}
pub fn clear(&mut self) {
self.len = 0;
}
#[inline]
pub fn push(&mut self, mv: Move) {
self.moves[self.len] = mv;
self.len += 1;
}
}
impl Default for MoveList {
fn default() -> Self {
MoveList::new()
}
}
impl Deref for MoveList {
type Target = [Move];
fn deref(&self) -> &[Move] {
&self.moves[..self.len]
}
}
impl fmt::Debug for MoveList {
fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
f.debug_list().entries(self.iter()).finish()
}
}
}
pub mod search {
use crate::cg_core::rng::Rng;
use crate::cg_search::Game;
use crate::uttt_engine::board::{Board, PatternPolicy, PlayoutPolicy, Status};
use crate::uttt_engine::moves::{Move, MoveList};
use crate::uttt_engine::value::Network;
impl Game for Board {
type Move = Move;
fn to_move(&self) -> usize {
Board::to_move(self)
}
fn legal_moves(&self, moves: &mut Vec<Move>) {
let mut list = MoveList::new();
Board::legal_moves(self, &mut list);
moves.clear();
moves.extend_from_slice(&list);
}
fn play(&mut self, mv: Move) {
Board::play(self, mv);
}
fn score(&self) -> Option<f64> {
score(self.status())
}
fn playout(&mut self, rng: &mut Rng) -> f64 {
score(self.decisive_playout(rng)).expect("a playout ends the game")
}
}
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct PolicyBoard {
pub board: Board,
pub policy: &'static PlayoutPolicy,
}
impl Game for PolicyBoard {
type Move = Move;
fn to_move(&self) -> usize {
self.board.to_move()
}
fn legal_moves(&self, moves: &mut Vec<Move>) {
Game::legal_moves(&self.board, moves);
}
fn play(&mut self, mv: Move) {
self.board.play(mv);
}
fn score(&self) -> Option<f64> {
score(self.board.status())
}
fn priors(&self, moves: &[Move], weights: &mut Vec<f32>) {
self.board.move_weights(self.policy, moves, weights);
}
fn playout(&mut self, rng: &mut Rng) -> f64 {
score(self.board.policy_playout(self.policy, rng)).expect("a playout ends the game")
}
}
#[derive(Clone, Copy)]
pub struct ValueBoard<const H: usize = 64, const H2: usize = 16> {
pub board: Board,
pub network: &'static Network<H, H2>,
}
impl<const H: usize, const H2: usize> ValueBoard<H, H2> {
pub fn estimate(&self) -> f64 {
network_estimate(&self.board, self.network)
}
}
fn network_estimate<const H: usize, const H2: usize>(
board: &Board,
network: &Network<H, H2>,
) -> f64 {
let value = if board.game_winning_move().is_some() {
1.0
} else {
f64::from(network.evaluate(board))
};
if board.to_move() == 0 {
value
} else {
1.0 - value
}
}
impl<const H: usize, const H2: usize> PartialEq for ValueBoard<H, H2> {
fn eq(&self, other: &Self) -> bool {
self.board == other.board
}
}
impl<const H: usize, const H2: usize> Game for ValueBoard<H, H2> {
type Move = Move;
fn to_move(&self) -> usize {
self.board.to_move()
}
fn legal_moves(&self, moves: &mut Vec<Move>) {
Game::legal_moves(&self.board, moves);
}
fn play(&mut self, mv: Move) {
self.board.play(mv);
}
fn score(&self) -> Option<f64> {
score(self.board.status())
}
fn playout(&mut self, _rng: &mut Rng) -> f64 {
self.estimate()
}
}
#[derive(Clone, Copy)]
pub struct MixBoard<const H: usize = 64, const H2: usize = 16> {
pub board: Board,
pub network: &'static Network<H, H2>,
pub policy: &'static PlayoutPolicy,
pub share: f64,
}
impl<const H: usize, const H2: usize> PartialEq for MixBoard<H, H2> {
fn eq(&self, other: &Self) -> bool {
self.board == other.board
}
}
impl<const H: usize, const H2: usize> Game for MixBoard<H, H2> {
type Move = Move;
fn to_move(&self) -> usize {
self.board.to_move()
}
fn legal_moves(&self, moves: &mut Vec<Move>) {
Game::legal_moves(&self.board, moves);
}
fn play(&mut self, mv: Move) {
self.board.play(mv);
}
fn score(&self) -> Option<f64> {
score(self.board.status())
}
fn playout(&mut self, rng: &mut Rng) -> f64 {
if self.board.game_winning_move().is_some() {
return network_estimate(&self.board, self.network);
}
let estimate = network_estimate(&self.board, self.network);
let mut board = self.board;
let played =
score(board.policy_playout(self.policy, rng)).expect("a playout ends the game");
self.share * estimate + (1.0 - self.share) * played
}
}
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct PatternBoard {
pub board: Board,
pub policy: &'static PatternPolicy,
}
impl Game for PatternBoard {
type Move = Move;
fn to_move(&self) -> usize {
self.board.to_move()
}
fn legal_moves(&self, moves: &mut Vec<Move>) {
Game::legal_moves(&self.board, moves);
}
fn play(&mut self, mv: Move) {
self.board.play(mv);
}
fn score(&self) -> Option<f64> {
score(self.board.status())
}
fn priors(&self, moves: &[Move], weights: &mut Vec<f32>) {
self.board.pattern_move_weights(self.policy, moves, weights);
}
fn playout(&mut self, rng: &mut Rng) -> f64 {
score(self.board.pattern_playout(self.policy, rng))
.expect("a playout ends the game")
}
}
pub fn score(status: Status) -> Option<f64> {
match status {
Status::Ongoing => None,
Status::Win(0) => Some(1.0),
Status::Win(_) => Some(0.0),
Status::Draw => Some(0.5),
}
}
}
pub mod value {
use crate::uttt_engine::board::Board;
pub const INPUTS: usize = 217;
pub const THEIR_CELLS: usize = 81;
pub const CLOSED: usize = 162;
pub const TARGET: usize = 189;
pub const THREATS: usize = 199;
pub const MAX_ACTIVE: usize = 128;
pub fn active_inputs(board: &Board, list: &mut [u16; MAX_ACTIVE]) -> usize {
let me = board.to_move();
let them = 1 - me;
let mut count = 0;
let mut push = |input: usize, count: &mut usize| {
list[*count] = input as u16;
*count += 1;
};
let closed = board.closed_boards();
for (seat, offset) in [(me, 0), (them, THEIR_CELLS)] {
for small in 0..9 {
if closed & (1 << small) != 0 {
continue;
}
let mut cells = board.cells(seat, small);
while cells != 0 {
push(
offset + 9 * small + cells.trailing_zeros() as usize,
&mut count,
);
cells &= cells - 1;
}
}
}
let mut boards = closed;
while boards != 0 {
let small = boards.trailing_zeros() as usize;
let status = if board.won_boards(me) & (1 << small) != 0 {
0
} else if board.won_boards(them) & (1 << small) != 0 {
1
} else {
2
};
push(CLOSED + 3 * small + status, &mut count);
boards &= boards - 1;
}
push(TARGET + board.target().unwrap_or(9), &mut count);
for (seat, offset) in [(me, THREATS), (them, THREATS + 9)] {
let mut threats = board.threat_boards(seat);
while threats != 0 {
push(offset + threats.trailing_zeros() as usize, &mut count);
threats &= threats - 1;
}
}
count
}
pub type ValueNetwork = Network<64, 16>;
#[derive(Clone, Debug, PartialEq)]
pub struct Network<const H: usize, const H2: usize> {
input: Vec<[f32; H]>,
input_bias: [f32; H],
hidden: Vec<[f32; H]>,
hidden_bias: [f32; H2],
output: [f32; H2],
output_bias: f32,
}
impl<const H: usize, const H2: usize> Network<H, H2> {
pub const GROUPS: [usize; 6] = [INPUTS * H, H, H2 * H, H2, H2, 1];
pub const PARAMETERS: usize = INPUTS * H + H + H2 * H + H2 + H2 + 1;
pub fn from_parameters(parameters: &[f32]) -> Result<Self, String> {
if parameters.len() != Self::PARAMETERS {
return Err(format!(
"{} parameters instead of {}",
parameters.len(),
Self::PARAMETERS
));
}
let mut rest = parameters;
let mut take = |count: usize| {
let (taken, after) = rest.split_at(count);
rest = after;
taken
};
let rows = |values: &[f32]| -> Vec<[f32; H]> {
values
.chunks_exact(H)
.map(|row| std::array::from_fn(|unit| row[unit]))
.collect()
};
Ok(Network {
input: rows(take(INPUTS * H)),
input_bias: copy(take(H)),
hidden: rows(take(H2 * H)),
hidden_bias: copy(take(H2)),
output: copy(take(H2)),
output_bias: take(1)[0],
})
}
pub fn decode(text: &str) -> Result<Self, String> {
let bytes = base64(text)?;
let expected = 4 * Self::GROUPS.len() + Self::PARAMETERS;
if bytes.len() != expected {
return Err(format!("{} bytes instead of {expected}", bytes.len()));
}
let mut parameters = Vec::with_capacity(Self::PARAMETERS);
let mut rest = &bytes[..];
for count in Self::GROUPS {
let scale = f32::from_le_bytes([rest[0], rest[1], rest[2], rest[3]]);
let values = &rest[4..4 + count];
parameters.extend(values.iter().map(|&byte| f32::from(byte as i8) * scale));
rest = &rest[4 + count..];
}
Self::from_parameters(&parameters)
}
pub fn evaluate(&self, board: &Board) -> f32 {
let mut list = [0; MAX_ACTIVE];
let count = active_inputs(board, &mut list);
self.evaluate_inputs(&list[..count])
}
pub fn evaluate_inputs(&self, active: &[u16]) -> f32 {
let mut first = self.input_bias;
for &input in active {
for (value, weight) in first.iter_mut().zip(&self.input[usize::from(input)]) {
*value += weight;
}
}
for value in &mut first {
*value = value.clamp(0.0, 1.0);
}
let mut second = self.hidden_bias;
for (value, row) in second.iter_mut().zip(&self.hidden) {
*value = (*value + dot(&first, row)).clamp(0.0, 1.0);
}
let z = self.output_bias + dot(&second, &self.output);
1.0 / (1.0 + (-z).exp())
}
}
fn copy<const N: usize>(values: &[f32]) -> [f32; N] {
std::array::from_fn(|index| values[index])
}
fn dot(a: &[f32], b: &[f32]) -> f32 {
let mut lanes = [0.0f32; 8];
for (x, y) in a.chunks_exact(8).zip(b.chunks_exact(8)) {
for (lane, (x, y)) in lanes.iter_mut().zip(x.iter().zip(y)) {
*lane += x * y;
}
}
let tail: f32 = a
.chunks_exact(8)
.remainder()
.iter()
.zip(b.chunks_exact(8).remainder())
.map(|(x, y)| x * y)
.sum();
lanes.iter().sum::<f32>() + tail
}
fn base64(text: &str) -> Result<Vec<u8>, String> {
let mut out = Vec::with_capacity(text.len() / 4 * 3);
let (mut buffer, mut bits) = (0u32, 0);
for byte in text.bytes() {
let value = match byte {
b'A'..=b'Z' => byte - b'A',
b'a'..=b'z' => byte - b'a' + 26,
b'0'..=b'9' => byte - b'0' + 52,
b'+' => 62,
b'/' => 63,
b'=' => break,
_ => return Err(format!("{:?} is not base64", char::from(byte))),
};
buffer = buffer << 6 | u32::from(value);
bits += 6;
if bits >= 8 {
bits -= 8;
out.push((buffer >> bits) as u8);
buffer &= (1 << bits) - 1;
}
}
Ok(out)
}
}
pub use board::{Board, PatternPolicy, PlayoutPolicy, Status};
pub use moves::{Move, MoveList};
}
