// Bundled by cg-bundler from the `uttt-bot-mcts` package. Do not edit this file:
// change the sources in the repository and bundle again.
// Workspace crates included below: cg_core, cg_search, uttt_engine.

//! Monte Carlo tree search Ultimate Tic-Tac-Toe bot.
//!
//! Every turn it searches the current position with UCT and uniformly
//! random playouts (`cg-search`, `uttt-engine`), for most of the turn's time
//! limit, then plays the move it tried most often. The search keeps the
//! part of its tree under the moves played since its previous search, and
//! proves wins and losses near the end of the game: it plays a proven win,
//! avoids proven losses, and stops searching once the position is proven.
//! A move that wins the game at once is played without searching, and so is
//! the only action offered.
//!
//! It tracks the position from the opponent's moves but only plays actions
//! from the list it receives. Each turn it prints one line to stderr:
//! iterations, visits kept from earlier searches, the expected score of its
//! move (or the proven result), and the time it took.
//!
//! The seed comes from `CG_SEED` when the arena sets it, otherwise from the
//! clock. The arena may scale time limits with `CG_TIME_SCALE`, and
//! `CG_FIXED_ITERS` replaces the time budget by a number of iterations.

use std::io::{self, BufRead, Write};
use std::time::{Duration, Instant};

use crate::cg_core::input::{Input, InputError};
use crate::cg_core::rng::{seed_from_env_or_clock, Rng};
use crate::cg_search::{Budget, Mcts};
use crate::uttt_engine::{Board, Move};

/// CodinGame's time limit for the first answer.
const FIRST_LIMIT: Duration = Duration::from_millis(1000);
/// CodinGame's time limit for every later answer.
const LIMIT: Duration = Duration::from_millis(100);
/// Share of the limit the search may use.
const SHARE: f64 = 0.9;
/// Time kept for reading, writing and timing noise, at CodinGame's limits:
/// the search gets 82 ms of 100. With 2 ms (88 ms), answers reached 95 ms
/// on GitHub's runners and rarely went over 100 (about 1 game in 3,000 at
/// full time); on a busy 2-core machine the bot's own clock read up to
/// 97 ms. Scaled with the arena's time factor, like the limit.
const RESERVE: Duration = Duration::from_millis(8);
/// The exploration constant of UCB1, from matches on 2026-10-07 (time
/// scale 0.2, 200 pairs each): 0.5 beat 1.0 by 164 Elo, 0.7 beat 1.0 by
/// 116, 1.4 lost to 1.0 by 108, and 0.4 and 0.3 lost to 0.5 by 28 and 116.
/// At full time, 0.5 beat 1.0 by 162.
const EXPLORATION: f64 = 0.5;

fn main() {
    let seed = seed_from_env_or_clock();
    eprintln!("mcts: seed {seed}");
    let mut rng = Rng::new(seed);
    let mut mcts = Mcts::new(EXPLORATION, rng.next_u64());
    let stdin = io::stdin();
    let result = play(
        &mut mcts,
        &mut rng,
        Input::new(stdin.lock()),
        io::stdout().lock(),
        &mut io::stderr(),
        |start, limit| Budget::for_turn(start, limit, SHARE, RESERVE),
    );
    match result {
        Ok(()) | Err(InputError::Eof) => {}
        Err(err) => {
            eprintln!("mcts: {err}");
            std::process::exit(1);
        }
    }
}

/// Plays turns until the input ends. `budget` gives the search budget of a
/// turn from its start and CodinGame's limit for it.
fn play(
    mcts: &mut Mcts<Board>,
    rng: &mut Rng,
    mut input: Input<impl BufRead>,
    mut out: impl Write,
    log: &mut impl Write,
    budget: impl Fn(Instant, Duration) -> Budget,
) -> Result<(), InputError> {
    let io_error = |err: io::Error| InputError::Io(err.to_string());
    // `None` once the position is lost track of; then the bot plays at random.
    let mut board = Some(Board::new());
    let mut actions = Vec::new();
    let mut limit = FIRST_LIMIT;
    loop {
        let opponent: (i32, i32) = input.two()?;
        let start = Instant::now();
        let count: usize = input.one()?;
        actions.clear();
        for _ in 0..count {
            actions.push(input.two::<i32, i32>()?);
        }
        if actions.is_empty() {
            return Err(InputError::Parse {
                line: count.to_string(),
                expected: "at least one valid action".to_string(),
            });
        }

        let tracked = board.is_some();
        if opponent != (-1, -1) {
            board = board.and_then(|position| apply(position, opponent));
        }
        let moves: Option<Vec<Move>> = actions.iter().map(|&action| to_move(action)).collect();
        let position = match (board, moves) {
            (Some(position), Some(moves)) if moves.iter().all(|&mv| position.is_legal(mv)) => {
                Some((position, moves))
            }
            _ => None,
        };
        let choice = match position {
            Some((position, moves)) => {
                let mv = if moves.len() == 1 {
                    moves[0]
                } else {
                    let result = mcts.search(&position, &moves, budget(start, limit));
                    let outlook = match result.proven {
                        Some(true) => "proven win".to_string(),
                        Some(false) => "proven loss".to_string(),
                        None => format!("expected score {:.3}", result.expected_score),
                    };
                    writeln!(
                        log,
                        "mcts: {} iterations, {} kept, {outlook}, {} ms",
                        result.iterations,
                        result.reused,
                        start.elapsed().as_millis()
                    )
                    .map_err(io_error)?;
                    result.best
                };
                board = Some(apply_move(position, mv));
                actions[moves.iter().position(|&m| m == mv).expect("a candidate")]
            }
            None => {
                if tracked {
                    writeln!(log, "mcts: lost track of the position; playing at random")
                        .map_err(io_error)?;
                }
                board = None;
                *rng.pick(&actions).expect("the list is not empty")
            }
        };
        writeln!(out, "{} {}", choice.0, choice.1)
            .and_then(|()| out.flush())
            .map_err(io_error)?;
        limit = LIMIT;
    }
}

fn to_move((row, col): (i32, i32)) -> Option<Move> {
    Move::from_row_col(usize::try_from(row).ok()?, usize::try_from(col).ok()?)
}

/// The position after `action`, or `None` if it is not legal there.
fn apply(board: Board, action: (i32, i32)) -> Option<Board> {
    let mv = to_move(action)?;
    board.is_legal(mv).then(|| apply_move(board, mv))
}

fn apply_move(mut board: Board, mv: Move) -> Board {
    board.play(mv);
    board
}

#[allow(dead_code, unused_imports)]
mod cg_core {
    //! Code shared by bots: reading CodinGame input, a seeded random generator
    //! and the arena's time factor.
    //!
    //! This crate uses the standard library only. `cg-bundler` copies it into
    //! every bot that depends on it, so the result still compiles on CodinGame.

    pub mod input {
        //! Reading the referee's input, line by line.

        use std::fmt;
        use std::io::BufRead;
        use std::str::FromStr;

        /// Why reading input failed.
        #[derive(Clone, Debug, PartialEq, Eq)]
        pub enum InputError {
            /// The input ended: the game is over or the referee stopped.
            Eof,
            /// The input could not be read.
            Io(String),
            /// A line did not hold what was expected.
            Parse { line: String, expected: String },
        }

        impl fmt::Display for InputError {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                match self {
                    InputError::Eof => write!(f, "input ended"),
                    InputError::Io(err) => write!(f, "cannot read input: {err}"),
                    InputError::Parse { line, expected } => {
                        write!(f, "expected {expected}, got {line:?}")
                    }
                }
            }
        }

        impl std::error::Error for InputError {}

        /// Reads the referee's input one line at a time.
        ///
        /// ```
        /// use crate::cg_core::input::Input;
        ///
        /// let mut input = Input::new("-1 -1\n2\n4 4\n0 8\n".as_bytes());
        /// let opponent: (i32, i32) = input.two().unwrap();
        /// let count: usize = input.one().unwrap();
        /// assert_eq!((opponent, count), ((-1, -1), 2));
        /// ```
        pub struct Input<R> {
            reader: R,
            line: String,
        }

        impl<R: BufRead> Input<R> {
            pub fn new(reader: R) -> Self {
                Input {
                    reader,
                    line: String::new(),
                }
            }

            /// The next line, without its line ending.
            pub fn line(&mut self) -> Result<&str, InputError> {
                self.line.clear();
                match self.reader.read_line(&mut self.line) {
                    Ok(0) => Err(InputError::Eof),
                    Ok(_) => Ok(self.line.trim_end_matches(['\n', '\r'])),
                    Err(err) => Err(InputError::Io(err.to_string())),
                }
            }

            /// The next line, parsed as one value.
            pub fn one<T: FromStr>(&mut self) -> Result<T, InputError> {
                let line = self.line()?;
                line.trim().parse().map_err(|_| parse_error::<T>(line, 1))
            }

            /// The next line, parsed as two whitespace-separated values.
            pub fn two<A: FromStr, B: FromStr>(&mut self) -> Result<(A, B), InputError> {
                let line = self.line()?;
                let mut parts = line.split_whitespace();
                match (
                    parts.next().map(str::parse::<A>),
                    parts.next().map(str::parse::<B>),
                    parts.next(),
                ) {
                    (Some(Ok(a)), Some(Ok(b)), None) => Ok((a, b)),
                    _ => Err(InputError::Parse {
                        line: line.to_string(),
                        expected: format!(
                            "two values ({}, {})",
                            std::any::type_name::<A>(),
                            std::any::type_name::<B>()
                        ),
                    }),
                }
            }

            /// The next line, parsed as whitespace-separated values of one type.
            pub fn many<T: FromStr>(&mut self) -> Result<Vec<T>, InputError> {
                let line = self.line()?;
                line.split_whitespace()
                    .map(str::parse)
                    .collect::<Result<_, _>>()
                    .map_err(|_| parse_error::<T>(line, 0))
            }
        }

        fn parse_error<T>(line: &str, count: usize) -> InputError {
            let what = std::any::type_name::<T>();
            InputError::Parse {
                line: line.to_string(),
                expected: match count {
                    1 => format!("one value ({what})"),
                    _ => format!("values ({what})"),
                },
            }
        }
    }
    pub mod rng {
        //! Seeded pseudo-random numbers: xoshiro256++, seeded through SplitMix64.
        //!
        //! Not for cryptography. The same seed gives the same sequence on every
        //! platform, which makes local matches reproducible.

        use std::time::{SystemTime, UNIX_EPOCH};

        /// Environment variable the arena sets to give each bot a reproducible seed.
        /// CodinGame never sets it.
        pub const SEED_ENV: &str = "CG_SEED";

        /// The seed from `CG_SEED` when it is set to an integer, otherwise one
        /// derived from the clock.
        pub fn seed_from_env_or_clock() -> u64 {
            parse_seed(std::env::var(SEED_ENV).ok().as_deref()).unwrap_or_else(clock_seed)
        }

        fn parse_seed(value: Option<&str>) -> Option<u64> {
            value?.trim().parse().ok()
        }

        fn clock_seed() -> u64 {
            let nanos = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map(|elapsed| elapsed.as_nanos() as u64)
                .unwrap_or(0);
            // The address of a local variable differs between runs, which separates
            // two processes started in the same nanosecond.
            let local = 0u8;
            let address = &local as *const u8 as u64;
            nanos ^ address.rotate_left(32)
        }

        /// Fast, seedable random number generator (xoshiro256++).
        #[derive(Clone, Debug)]
        pub struct Rng {
            state: [u64; 4],
        }

        impl Rng {
            /// A generator whose whole sequence is determined by `seed`.
            pub fn new(seed: u64) -> Self {
                let mut mix = seed;
                Rng {
                    state: [
                        split_mix(&mut mix),
                        split_mix(&mut mix),
                        split_mix(&mut mix),
                        split_mix(&mut mix),
                    ],
                }
            }

            /// The next 64 random bits.
            #[inline]
            pub fn next_u64(&mut self) -> u64 {
                let [s0, s1, s2, s3] = &mut self.state;
                let result = s0.wrapping_add(*s3).rotate_left(23).wrapping_add(*s0);
                let t = *s1 << 17;
                *s2 ^= *s0;
                *s3 ^= *s1;
                *s1 ^= *s2;
                *s0 ^= *s3;
                *s2 ^= t;
                *s3 = s3.rotate_left(45);
                result
            }

            /// A uniformly random integer in `0..n`, without bias (Lemire's method).
            ///
            /// # Panics
            ///
            /// If `n` is 0.
            #[inline]
            pub fn below(&mut self, n: u64) -> u64 {
                assert!(n > 0, "Rng::below(0) has no possible value");
                let mut product = u128::from(self.next_u64()) * u128::from(n);
                if (product as u64) < n {
                    let threshold = n.wrapping_neg() % n;
                    while (product as u64) < threshold {
                        product = u128::from(self.next_u64()) * u128::from(n);
                    }
                }
                (product >> 64) as u64
            }

            /// A uniformly random float in `[0, 1)`.
            pub fn unit(&mut self) -> f64 {
                (self.next_u64() >> 11) as f64 * (1.0 / (1u64 << 53) as f64)
            }

            /// A uniformly random element of `items`, or `None` if it is empty.
            pub fn pick<'a, T>(&mut self, items: &'a [T]) -> Option<&'a T> {
                if items.is_empty() {
                    None
                } else {
                    items.get(self.below(items.len() as u64) as usize)
                }
            }

            /// Shuffles `items` uniformly (Fisher-Yates).
            pub fn shuffle<T>(&mut self, items: &mut [T]) {
                for i in (1..items.len()).rev() {
                    let j = self.below(i as u64 + 1) as usize;
                    items.swap(i, j);
                }
            }
        }

        fn split_mix(state: &mut u64) -> u64 {
            *state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
            let mut z = *state;
            z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
            z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
            z ^ (z >> 31)
        }
    }
    pub mod time {
        //! Time budgets.
        //!
        //! The arena can play games with shorter (or longer) time limits than
        //! CodinGame's, to test faster. It tells bots the factor in `CG_TIME_SCALE`;
        //! bots multiply their own time budget by [`time_scale`]. CodinGame never
        //! sets the variable, so there the factor is 1.

        /// Environment variable carrying the time factor.
        pub const TIME_SCALE_ENV: &str = "CG_TIME_SCALE";

        /// The factor from `CG_TIME_SCALE`, or 1 when it is unset or not a
        /// positive number.
        pub fn time_scale() -> f64 {
            parse_time_scale(std::env::var(TIME_SCALE_ENV).ok().as_deref())
        }

        fn parse_time_scale(value: Option<&str>) -> f64 {
            value
                .and_then(|text| text.trim().parse::<f64>().ok())
                .filter(|scale| scale.is_finite() && *scale > 0.0)
                .unwrap_or(1.0)
        }
    }
}

#[allow(dead_code, unused_imports)]
mod cg_search {
    //! Game-independent search for bots.
    //!
    //! - [`game`]: what a game must offer to be searched.
    //! - [`mcts`]: Monte Carlo tree search (UCT).
    //! - [`budget`]: how long a search may run, from the turn's time limit, the
    //!   arena's time scale, or a fixed number of iterations for tests.
    //!
    //! This crate uses the standard library only, so the bundler can copy it
    //! into bots.

    pub mod budget {
        //! How long a search may run.

        use std::time::{Duration, Instant};

        use crate::cg_core::time::time_scale;

        /// Environment variable that replaces time budgets by a fixed number of
        /// iterations, for reproducible tests. CodinGame never sets it.
        pub const FIXED_ITERATIONS_ENV: &str = "CG_FIXED_ITERS";

        /// When a search stops.
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum Budget {
            /// At this instant.
            Until(Instant),
            /// After this many iterations, however long they take.
            Iterations(u64),
        }

        impl Budget {
            /// The budget of a turn that started at `start`, when the game allows
            /// `limit` per answer on CodinGame.
            ///
            /// With `CG_FIXED_ITERS` set, a fixed number of iterations. Otherwise
            /// the search uses `share` of the limit minus `reserve` (kept for
            /// reading, writing and timing noise on CodinGame), all scaled by the
            /// arena's time factor ([`time_scale`]). Scaling the reserve too keeps
            /// scaled games proportional to real ones; the arena absorbs the noise
            /// of its own machine with a tolerance of its own (ADR 0013).
            pub fn for_turn(
                start: Instant,
                limit: Duration,
                share: f64,
                reserve: Duration,
            ) -> Budget {
                match fixed_iterations(std::env::var(FIXED_ITERATIONS_ENV).ok().as_deref()) {
                    Some(iterations) => Budget::Iterations(iterations),
                    None => Budget::Until(start + search_time(limit, time_scale(), share, reserve)),
                }
            }

            /// Whether a search that ran `iterations` iterations must stop.
            #[inline]
            pub fn is_spent(&self, iterations: u64) -> bool {
                match *self {
                    Budget::Until(deadline) => Instant::now() >= deadline,
                    Budget::Iterations(limit) => iterations >= limit,
                }
            }
        }

        /// The search time for a turn: `share` of the limit minus `reserve`, times
        /// `scale`, and never negative.
        fn search_time(limit: Duration, scale: f64, share: f64, reserve: Duration) -> Duration {
            limit.mul_f64(share).saturating_sub(reserve).mul_f64(scale)
        }

        fn fixed_iterations(value: Option<&str>) -> Option<u64> {
            value?.trim().parse().ok().filter(|&n| n > 0)
        }
    }
    pub mod game {
        //! What a game must offer to be searched.

        use crate::cg_core::rng::Rng;

        /// A two-player game of perfect information in which players take turns.
        ///
        /// The position is cloned at every search iteration, so it should be small
        /// and cheap to copy. Positions are compared to find the current one in the
        /// tree of an earlier search.
        pub trait Game: Clone + PartialEq {
            type Move: Copy + PartialEq + std::fmt::Debug;

            /// The player to move: 0 or 1.
            fn to_move(&self) -> usize;

            /// Replaces the content of `moves` with the legal moves. There is at
            /// least one while the game goes on.
            fn legal_moves(&self, moves: &mut Vec<Self::Move>);

            /// Plays a legal move for the player to move.
            fn play(&mut self, mv: Self::Move);

            /// Player 0's score once the game is over: 1 for a win, 0.5 for a draw,
            /// 0 for a loss. `None` while the game goes on.
            fn score(&self) -> Option<f64>;

            /// Plays to the end and returns player 0's score. The default plays
            /// uniformly random legal moves; games may provide a faster or smarter
            /// version.
            fn playout(&mut self, rng: &mut Rng) -> f64 {
                let mut moves = Vec::new();
                loop {
                    if let Some(score) = self.score() {
                        return score;
                    }
                    self.legal_moves(&mut moves);
                    let mv = *rng.pick(&moves).expect("a game that goes on has moves");
                    self.play(mv);
                }
            }
        }
    }
    pub mod mcts {
        //! Monte Carlo tree search with the UCT selection rule.
        //!
        //! Each iteration walks down the tree from the root, at each node taking
        //! the child with the best upper confidence bound (UCB1), until it reaches a
        //! child never tried. It plays the game to the end from there (the
        //! playout), then adds the result to every node on the way. A node gets its
        //! children the second time an iteration reaches it, all at once, in random
        //! order. The move played is the root child tried most often, except that
        //! a move winning the game at once is played without searching.
        //!
        //! The tree lives in one vector, children of a node next to each other. It
        //! is kept from one search to the next: when the new position is one or two
        //! moves below the previous root (the bot's move, then the opponent's), the
        //! subtree of that position becomes the new tree, with the visits it
        //! already has; otherwise the search starts afresh.
        //!
        //! The search also proves wins and losses (MCTS-Solver): a position where
        //! the game is won or lost is proven, a node is lost for the player who
        //! moved into it when the opponent has a proven winning answer, and won
        //! when every answer is proven lost. Iterations that reach a proven node
        //! use its exact result, selection never picks an answer proven lost when
        //! another exists, a proven win at the root is played at once, and the
        //! search stops when the root is proven. Draws are not proven.

        use crate::cg_core::rng::Rng;

        use crate::cg_search::budget::Budget;
        use crate::cg_search::game::Game;

        /// What is proven about a node, for the player who moved into it.
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        enum Proof {
            Unknown,
            /// The mover wins whatever the opponent does.
            MoverWins,
            /// The opponent has a winning answer.
            MoverLoses,
        }

        /// One position of the tree, reached by `mv`.
        #[derive(Clone, Copy, Debug)]
        struct Node<M> {
            /// The move that leads here; unused at the root.
            mv: M,
            /// The player who played `mv`, whose point of view `value` and `proof`
            /// take.
            mover: u8,
            proof: Proof,
            /// Whether the children have been created; a node of a finished game
            /// has none.
            expanded: bool,
            first_child: u32,
            children: u32,
            visits: u32,
            /// The mover's average score over the visits.
            value: f32,
            /// `1 / sqrt(visits)`, kept so that selection, which reads every child
            /// of a node, needs no division or square root.
            inv_sqrt_visits: f32,
        }

        /// What a search found.
        #[derive(Clone, Debug, PartialEq)]
        pub struct SearchResult<M> {
            /// The root move tried most often.
            pub best: M,
            /// Iterations run by this search.
            pub iterations: u64,
            /// Visits the root already had from earlier searches.
            pub reused: u64,
            /// `Some(true)` when the player to move is proven to win, `Some(false)`
            /// when proven to lose, `None` when not proven.
            pub proven: Option<bool>,
            /// The average score of `best` for the player to move, from 0 to 1.
            pub expected_score: f64,
            /// Nodes in the tree.
            pub nodes: usize,
        }

        /// A Monte Carlo tree search, reusable from turn to turn.
        pub struct Mcts<G: Game> {
            /// The exploration constant `c` of UCB1: a child's bound is its average
            /// score plus `c · sqrt(ln(parent visits) / visits)`.
            pub exploration: f64,
            rng: Rng,
            nodes: Vec<Node<G::Move>>,
            /// The position at the root of `nodes`, once a search has run.
            root: Option<G>,
            /// Spare storage for moving a subtree to the front, kept to avoid
            /// allocating every turn.
            spare: Vec<Node<G::Move>>,
            origin: Vec<u32>,
            moves: Vec<G::Move>,
            path: Vec<u32>,
        }

        impl<G: Game> Mcts<G> {
            pub fn new(exploration: f64, seed: u64) -> Self {
                Mcts {
                    exploration,
                    rng: Rng::new(seed),
                    nodes: Vec::new(),
                    root: None,
                    spare: Vec::new(),
                    origin: Vec::new(),
                    moves: Vec::new(),
                    path: Vec::new(),
                }
            }

            /// Searches `root` and returns the best of `candidates`, which must be
            /// legal there (CodinGame's list, for example). Returns a candidate that
            /// wins at once without searching; otherwise keeps what earlier
            /// searches learned about `root`, runs at least one iteration per
            /// candidate, then runs until `budget` is spent.
            ///
            /// # Panics
            ///
            /// If `candidates` is empty or the game is over.
            pub fn search(
                &mut self,
                root: &G,
                candidates: &[G::Move],
                budget: Budget,
            ) -> SearchResult<G::Move> {
                assert!(!candidates.is_empty(), "nothing to choose from");
                assert!(root.score().is_none(), "the game is over");
                let win = if root.to_move() == 0 { 1.0 } else { 0.0 };
                for &mv in candidates {
                    let mut next = root.clone();
                    next.play(mv);
                    if next.score() == Some(win) {
                        return SearchResult {
                            best: mv,
                            iterations: 0,
                            reused: 0,
                            proven: Some(true),
                            expected_score: 1.0,
                            nodes: self.nodes.len(),
                        };
                    }
                }

                if !self.reuse(root, candidates) {
                    self.start(root, candidates);
                }
                self.root = Some(root.clone());
                let reused = u64::from(self.nodes[0].visits);

                let mut iterations = 0;
                while self.nodes[0].proof == Proof::Unknown
                    && ((iterations as usize) < candidates.len() || !budget.is_spent(iterations))
                {
                    self.iterate(root);
                    iterations += 1;
                }

                // A proven win, else the most tried answer not proven lost.
                let children = || self.children(0).map(|index| &self.nodes[index]);
                let best = children()
                    .find(|child| child.proof == Proof::MoverWins)
                    .or_else(|| {
                        children()
                            .filter(|child| child.proof != Proof::MoverLoses)
                            .max_by_key(|child| child.visits)
                    })
                    .or_else(|| children().max_by_key(|child| child.visits))
                    .expect("the root has children");
                let proven = match self.nodes[0].proof {
                    Proof::Unknown => None,
                    // The root's mover is the opponent of the player to move.
                    Proof::MoverWins => Some(false),
                    Proof::MoverLoses => Some(true),
                };
                let expected_score = match best.proof {
                    Proof::MoverWins => 1.0,
                    Proof::MoverLoses => 0.0,
                    Proof::Unknown => f64::from(best.value),
                };
                SearchResult {
                    best: best.mv,
                    iterations,
                    reused,
                    proven,
                    expected_score,
                    nodes: self.nodes.len(),
                }
            }

            /// A fresh tree: the root and one child per candidate.
            fn start(&mut self, root: &G, candidates: &[G::Move]) {
                self.nodes.clear();
                self.nodes.push(Node {
                    mv: candidates[0],
                    mover: (1 - root.to_move()) as u8,
                    proof: Proof::Unknown,
                    expanded: false,
                    first_child: 0,
                    children: 0,
                    visits: 0,
                    value: 0.0,
                    inv_sqrt_visits: 0.0,
                });
                self.moves.clear();
                self.moves.extend_from_slice(candidates);
                self.expand(0, root.to_move());
            }

            /// Makes the node of `root`, if the tree holds it within two moves of
            /// its current root, the new root, and drops the rest of the tree.
            /// Returns whether it did. The kept root must offer exactly
            /// `candidates`.
            fn reuse(&mut self, root: &G, candidates: &[G::Move]) -> bool {
                let Some(node) = self.find(root) else {
                    return false;
                };
                let kept = &self.nodes[node];
                let same_moves = kept.expanded
                    && kept.children as usize == candidates.len()
                    && self
                        .children(node)
                        .all(|child| candidates.contains(&self.nodes[child].mv));
                if !same_moves {
                    return false;
                }
                if node != 0 {
                    self.keep_subtree(node);
                }
                true
            }

            /// The node holding `position`: the root or a node one or two moves
            /// below it.
            fn find(&self, position: &G) -> Option<usize> {
                let previous = self.root.as_ref()?;
                if previous == position {
                    return Some(0);
                }
                for child in self.children(0) {
                    let mut after_one = previous.clone();
                    after_one.play(self.nodes[child].mv);
                    if &after_one == position {
                        return Some(child);
                    }
                    for grandchild in self.children(child) {
                        let mut after_two = after_one.clone();
                        after_two.play(self.nodes[grandchild].mv);
                        if &after_two == position {
                            return Some(grandchild);
                        }
                    }
                }
                None
            }

            /// Moves the subtree of `node` to the front of the tree, `node` first,
            /// and drops every other node.
            fn keep_subtree(&mut self, node: usize) {
                self.spare.clear();
                self.origin.clear();
                self.spare.push(self.nodes[node]);
                self.origin.push(node as u32);
                let mut next = 0;
                while next < self.spare.len() {
                    let old = self.nodes[self.origin[next] as usize];
                    if old.expanded {
                        self.spare[next].first_child = self.spare.len() as u32;
                        for child in old.first_child..old.first_child + old.children {
                            self.spare.push(self.nodes[child as usize]);
                            self.origin.push(child);
                        }
                    }
                    next += 1;
                }
                std::mem::swap(&mut self.nodes, &mut self.spare);
            }

            /// The indices of the children of `node`.
            fn children(&self, node: usize) -> std::ops::Range<usize> {
                let node = &self.nodes[node];
                let first = node.first_child as usize;
                first
                    ..first
                        + if node.expanded {
                            node.children as usize
                        } else {
                            0
                        }
            }

            /// One iteration: selection, expansion, playout, backpropagation, and
            /// proofs.
            fn iterate(&mut self, root: &G) {
                let mut state = root.clone();
                let mut node = 0;
                let mut proved = false;
                self.path.clear();
                self.path.push(0);
                let score = loop {
                    let current = self.nodes[node];
                    let mover_score = |wins: bool| {
                        if wins == (current.mover == 0) {
                            1.0
                        } else {
                            0.0
                        }
                    };
                    match current.proof {
                        Proof::MoverWins => break mover_score(true),
                        Proof::MoverLoses => break mover_score(false),
                        Proof::Unknown => {}
                    }
                    if let Some(score) = state.score() {
                        if node != 0 && score != 0.5 {
                            let wins = score == mover_score(true);
                            self.nodes[node].proof = if wins {
                                Proof::MoverWins
                            } else {
                                Proof::MoverLoses
                            };
                            proved = true;
                        }
                        break score;
                    }
                    if !current.expanded {
                        if self.nodes[node].visits == 0 {
                            // A new leaf: estimate it with one playout.
                            break state.playout(&mut self.rng);
                        }
                        state.legal_moves(&mut self.moves);
                        self.expand(node, state.to_move());
                    }
                    node = self.select(node);
                    state.play(self.nodes[node].mv);
                    self.path.push(node as u32);
                };
                for &index in &self.path {
                    let node = &mut self.nodes[index as usize];
                    node.visits += 1;
                    let mover_score = if node.mover == 0 { score } else { 1.0 - score };
                    let visits = node.visits as f32;
                    node.value += (mover_score as f32 - node.value) / visits;
                    node.inv_sqrt_visits = visits.sqrt().recip();
                }
                if proved {
                    self.prove_ancestors();
                }
            }

            /// Proves the nodes on the current path, from the leaf up, as far as
            /// their children allow: a node whose opponent has a proven winning
            /// answer is lost for its mover, and one whose answers are all proven
            /// lost is won.
            fn prove_ancestors(&mut self) {
                for depth in (0..self.path.len() - 1).rev() {
                    let node = self.path[depth] as usize;
                    let mut all_lost = true;
                    let mut proof = Proof::Unknown;
                    for child in self.children(node) {
                        match self.nodes[child].proof {
                            Proof::MoverWins => {
                                proof = Proof::MoverLoses;
                                break;
                            }
                            Proof::MoverLoses => {}
                            Proof::Unknown => all_lost = false,
                        }
                    }
                    if proof == Proof::Unknown && all_lost {
                        proof = Proof::MoverWins;
                    }
                    if proof == Proof::Unknown {
                        return;
                    }
                    self.nodes[node].proof = proof;
                }
            }

            /// Gives `node` one child per move in `self.moves`, in random order.
            fn expand(&mut self, node: usize, to_move: usize) {
                self.rng.shuffle(&mut self.moves);
                let first_child = self.nodes.len() as u32;
                for &mv in &self.moves {
                    self.nodes.push(Node {
                        mv,
                        mover: to_move as u8,
                        proof: Proof::Unknown,
                        expanded: false,
                        first_child: 0,
                        children: 0,
                        visits: 0,
                        value: 0.0,
                        inv_sqrt_visits: 0.0,
                    });
                }
                let parent = &mut self.nodes[node];
                parent.expanded = true;
                parent.first_child = first_child;
                parent.children = self.moves.len() as u32;
            }

            /// The child of `node` with the highest UCB1 bound, an untried child
            /// first, never a child proven lost for the player choosing unless all
            /// are.
            fn select(&self, node: usize) -> usize {
                let parent = &self.nodes[node];
                let first = parent.first_child as usize;
                let children = &self.nodes[first..first + parent.children as usize];
                // UCB1: value + c * sqrt(ln(parent visits) / visits).
                let spread =
                    (self.exploration * f64::from(parent.visits.max(1)).ln().sqrt()) as f32;
                let mut best = 0;
                let mut best_bound = f32::NEG_INFINITY;
                for (offset, child) in children.iter().enumerate() {
                    match child.proof {
                        Proof::MoverLoses => continue,
                        Proof::MoverWins => return first + offset,
                        Proof::Unknown => {}
                    }
                    if child.visits == 0 {
                        return first + offset;
                    }
                    let bound = child.value + spread * child.inv_sqrt_visits;
                    if bound > best_bound {
                        best_bound = bound;
                        best = offset;
                    }
                }
                first + best
            }
        }
    }

    pub use budget::Budget;
    pub use game::Game;
    pub use mcts::{Mcts, SearchResult};
}

#[allow(dead_code, unused_imports)]
mod uttt_engine {
    //! Fast Ultimate Tic-Tac-Toe rules for bots, as described in
    //! `games/uttt/RULES.md`.
    //!
    //! The whole position fits in a few machine words and is `Copy`: search
    //! copies it instead of undoing moves. Each small board is a 9-bit mask per
    //! player, with cell `3 * row + col` at bit `3 * row + col`.
    //!
    //! The engine uses the standard library only, so the bundler can copy it
    //! into bots. [`search`] makes [`Board`] a game that `cg-search` can
    //! search. Its parity tests check it against the readable reference referee
    //! (`uttt-referee`) move by move.

    pub mod board {
        //! The position and the rules.

        use crate::cg_core::rng::Rng;

        use crate::uttt_engine::grid::{self, FULL};
        use crate::uttt_engine::moves::{Move, MoveList};

        /// Whether the game goes on, and how it ended.
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
        pub enum Status {
            Ongoing,
            /// The player in this seat won: 0 moved first.
            Win(usize),
            Draw,
        }

        /// Marker for "the player to move may choose any open small board".
        const ANY_BOARD: u8 = 9;

        /// An Ultimate Tic-Tac-Toe position. Small enough to copy freely.
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
        pub struct Board {
            /// `marks[seat][board]`: the cells of a small board marked by a seat.
            marks: [[u16; 9]; 2],
            /// `won[seat]`: the small boards a seat has won.
            won: [u16; 2],
            /// Small boards that are won or full; no more moves there.
            closed: u16,
            /// The small board the player to move must play in, or `ANY_BOARD`.
            target: u8,
            to_move: u8,
            status: Status,
        }

        impl Default for Board {
            fn default() -> Self {
                Board::new()
            }
        }

        impl Board {
            /// The starting position: empty, seat 0 to move, anywhere.
            pub fn new() -> Self {
                Board {
                    marks: [[0; 9]; 2],
                    won: [0; 2],
                    closed: 0,
                    target: ANY_BOARD,
                    to_move: 0,
                    status: Status::Ongoing,
                }
            }

            /// The seat to move: 0 or 1.
            #[inline]
            pub fn to_move(&self) -> usize {
                usize::from(self.to_move)
            }

            #[inline]
            pub fn status(&self) -> Status {
                self.status
            }

            /// The seat that marked the cell of `mv`, if any.
            pub fn mark(&self, mv: Move) -> Option<usize> {
                let bit = 1 << mv.cell();
                (0..2).find(|&seat| self.marks[seat][mv.board()] & bit != 0)
            }

            /// The seat that won small board `board`, if any.
            pub fn small_winner(&self, board: usize) -> Option<usize> {
                (0..2).find(|&seat| self.won[seat] & (1 << board) != 0)
            }

            /// Small boards won by each seat: the tiebreak points.
            pub fn points(&self) -> [u32; 2] {
                [self.won[0].count_ones(), self.won[1].count_ones()]
            }

            /// The small board the player to move is sent to, or `None` when it may
            /// play in any open small board.
            pub fn target(&self) -> Option<usize> {
                (self.target != ANY_BOARD).then_some(usize::from(self.target))
            }

            /// Whether small board `board` is won or full.
            pub fn is_closed(&self, board: usize) -> bool {
                self.closed & (1 << board) != 0
            }

            /// Empty cells of `board`, as a 9-bit mask.
            #[inline]
            fn empty_cells(&self, board: usize) -> u16 {
                !(self.marks[0][board] | self.marks[1][board]) & FULL
            }

            /// Whether the player to move may play `mv`.
            pub fn is_legal(&self, mv: Move) -> bool {
                let board = mv.board();
                self.status == Status::Ongoing
                    && !self.is_closed(board)
                    && (self.target == ANY_BOARD || usize::from(self.target) == board)
                    && self.empty_cells(board) & (1 << mv.cell()) != 0
            }

            /// Writes the legal moves into `moves`, by board then cell.
            pub fn legal_moves(&self, moves: &mut MoveList) {
                moves.clear();
                if self.status != Status::Ongoing {
                    return;
                }
                if self.target != ANY_BOARD {
                    self.push_board_moves(usize::from(self.target), moves);
                } else {
                    for board in grid::cells(!self.closed & FULL) {
                        self.push_board_moves(board, moves);
                    }
                }
            }

            #[inline]
            fn push_board_moves(&self, board: usize, moves: &mut MoveList) {
                for cell in grid::cells(self.empty_cells(board)) {
                    moves.push(Move::new(board, cell));
                }
            }

            /// Plays `mv` for the player to move. The move must be legal; this is
            /// checked in debug builds only, for speed.
            pub fn play(&mut self, mv: Move) {
                debug_assert!(self.is_legal(mv), "illegal move {mv} in {self:?}");
                let seat = usize::from(self.to_move);
                let (board, cell) = (mv.board(), mv.cell());
                self.marks[seat][board] |= 1 << cell;

                if grid::has_line(self.marks[seat][board]) {
                    self.won[seat] |= 1 << board;
                    self.closed |= 1 << board;
                    if grid::has_line(self.won[seat]) {
                        self.status = Status::Win(seat);
                    }
                } else if self.empty_cells(board) == 0 {
                    self.closed |= 1 << board;
                }

                self.target = if self.is_closed(cell) {
                    ANY_BOARD
                } else {
                    cell as u8
                };
                self.to_move ^= 1;

                if self.status == Status::Ongoing && self.closed == FULL {
                    let [zero, one] = self.points();
                    self.status = match zero.cmp(&one) {
                        std::cmp::Ordering::Greater => Status::Win(0),
                        std::cmp::Ordering::Less => Status::Win(1),
                        std::cmp::Ordering::Equal => Status::Draw,
                    };
                }
            }

            /// A uniformly random legal move, chosen without listing the moves. It
            /// draws the same number from `rng` as picking from
            /// [`legal_moves`](Board::legal_moves), and picks the same move for it.
            /// The game must go on.
            #[inline]
            pub fn random_move(&self, rng: &mut Rng) -> Move {
                debug_assert_eq!(self.status, Status::Ongoing);
                if self.target != ANY_BOARD {
                    let board = usize::from(self.target);
                    let empty = self.empty_cells(board);
                    let index = rng.below(u64::from(grid::count(empty))) as u32;
                    return Move::new_unchecked(board, grid::nth_cell(empty, index));
                }
                let open = !self.closed & FULL;
                let total: u32 = grid::cells(open)
                    .map(|board| grid::count(self.empty_cells(board)))
                    .sum();
                let mut index = rng.below(u64::from(total)) as u32;
                for board in grid::cells(open) {
                    let empty = self.empty_cells(board);
                    let count = grid::count(empty);
                    if index < count {
                        return Move::new_unchecked(board, grid::nth_cell(empty, index));
                    }
                    index -= count;
                }
                unreachable!("a game that goes on has a legal move")
            }

            /// Plays uniformly random legal moves until the game ends, and returns
            /// how it ended.
            pub fn random_playout(&mut self, rng: &mut Rng) -> Status {
                while self.status == Status::Ongoing {
                    let mv = self.random_move(rng);
                    self.play(mv);
                }
                self.status
            }
        }
    }
    pub mod grid {
        //! 3×3 grids as 9-bit masks: bit `3 * row + col` is the cell at
        //! `(row, col)`. Used for small boards and for the main board alike.

        /// All nine cells.
        pub const FULL: u16 = 0x1FF;

        /// The 8 lines of a 3×3 grid: 3 rows, 3 columns, 2 diagonals.
        pub const LINES: [u16; 8] = [
            0b000_000_111,
            0b000_111_000,
            0b111_000_000,
            0b001_001_001,
            0b010_010_010,
            0b100_100_100,
            0b100_010_001,
            0b001_010_100,
        ];

        const fn line_table() -> [bool; 512] {
            let mut table = [false; 512];
            let mut mask = 0;
            while mask < 512 {
                let mut line = 0;
                while line < LINES.len() {
                    if mask as u16 & LINES[line] == LINES[line] {
                        table[mask] = true;
                    }
                    line += 1;
                }
                mask += 1;
            }
            table
        }

        /// `HAS_LINE[mask]` is true when `mask` contains a whole line.
        static HAS_LINE: [bool; 512] = line_table();

        /// Whether the cells in `mask` contain a whole line.
        #[inline]
        pub fn has_line(mask: u16) -> bool {
            HAS_LINE[usize::from(mask & FULL)]
        }

        const fn cell_tables() -> ([u8; 512], [[u8; 9]; 512]) {
            let mut counts = [0; 512];
            let mut nth = [[0; 9]; 512];
            let mut mask = 0;
            while mask < 512 {
                let mut cell = 0;
                while cell < 9 {
                    if mask & (1 << cell) != 0 {
                        nth[mask][counts[mask] as usize] = cell as u8;
                        counts[mask] += 1;
                    }
                    cell += 1;
                }
                mask += 1;
            }
            (counts, nth)
        }

        /// `CELL_TABLES.0[mask]`: the cells in `mask`; `CELL_TABLES.1[mask][n]`:
        /// its `n`-th cell from the lowest. Tables, because CodinGame's compiler
        /// targets processors without a population-count instruction.
        static CELL_TABLES: ([u8; 512], [[u8; 9]; 512]) = cell_tables();

        /// The number of cells in `mask`.
        #[inline]
        pub fn count(mask: u16) -> u32 {
            u32::from(CELL_TABLES.0[usize::from(mask & FULL)])
        }

        /// The `n`-th cell of `mask`, counting from the lowest and from 0. `mask`
        /// must have more than `n` cells.
        #[inline]
        pub fn nth_cell(mask: u16, n: u32) -> usize {
            debug_assert!(n < count(mask), "fewer than {} cells", n + 1);
            usize::from(CELL_TABLES.1[usize::from(mask & FULL)][n as usize])
        }

        /// Iterates over the cells set in `mask`, lowest first.
        #[inline]
        pub fn cells(mut mask: u16) -> impl Iterator<Item = usize> {
            std::iter::from_fn(move || {
                if mask == 0 {
                    None
                } else {
                    let cell = mask.trailing_zeros() as usize;
                    mask &= mask - 1;
                    Some(cell)
                }
            })
        }
    }
    pub mod moves {
        //! Moves and fixed-capacity move lists.

        use std::fmt;
        use std::ops::Deref;

        /// A cell of the 9×9 board, stored as `9 * board + cell`: `board` is the
        /// small board (0 to 8, row-major) and `cell` the position inside it.
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
        pub struct Move(u8);

        impl Move {
            /// The move in cell `cell` of small board `board`, both from 0 to 8.
            ///
            /// # Panics
            ///
            /// If either index is above 8.
            pub fn new(board: usize, cell: usize) -> Move {
                assert!(board < 9 && cell < 9, "no cell {cell} in board {board}");
                Move((9 * board + cell) as u8)
            }

            /// The move in cell `cell` of small board `board`, both from 0 to 8,
            /// checked in debug builds only, for speed.
            #[inline]
            pub(crate) fn new_unchecked(board: usize, cell: usize) -> Move {
                debug_assert!(board < 9 && cell < 9, "no cell {cell} in board {board}");
                Move((9 * board + cell) as u8)
            }

            /// The move at CodinGame coordinates `(row, col)`, or `None` outside the
            /// 9×9 board.
            pub fn from_row_col(row: usize, col: usize) -> Option<Move> {
                (row < 9 && col < 9)
                    .then(|| Move::new(3 * (row / 3) + col / 3, 3 * (row % 3) + col % 3))
            }

            /// The small board, 0 to 8.
            #[inline]
            pub fn board(self) -> usize {
                usize::from(self.0 / 9)
            }

            /// The cell inside the small board, 0 to 8. It is also the small board
            /// the opponent is sent to.
            #[inline]
            pub fn cell(self) -> usize {
                usize::from(self.0 % 9)
            }

            /// CodinGame coordinates `(row, col)`.
            pub fn row_col(self) -> (usize, usize) {
                let (board, cell) = (self.board(), self.cell());
                (3 * (board / 3) + cell / 3, 3 * (board % 3) + cell % 3)
            }
        }

        impl fmt::Display for Move {
            /// Formats the move as CodinGame expects it: `row col`.
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                let (row, col) = self.row_col();
                write!(f, "{row} {col}")
            }
        }

        /// Up to 81 moves, without allocation.
        #[derive(Clone)]
        pub struct MoveList {
            moves: [Move; 81],
            len: usize,
        }

        impl MoveList {
            pub fn new() -> Self {
                MoveList {
                    moves: [Move(0); 81],
                    len: 0,
                }
            }

            pub fn clear(&mut self) {
                self.len = 0;
            }

            /// Adds a move. There is room for every cell of the board.
            #[inline]
            pub fn push(&mut self, mv: Move) {
                self.moves[self.len] = mv;
                self.len += 1;
            }
        }

        impl Default for MoveList {
            fn default() -> Self {
                MoveList::new()
            }
        }

        impl Deref for MoveList {
            type Target = [Move];

            fn deref(&self) -> &[Move] {
                &self.moves[..self.len]
            }
        }

        impl fmt::Debug for MoveList {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.debug_list().entries(self.iter()).finish()
            }
        }
    }
    pub mod search {
        //! The engine as a game for `cg-search`.

        use crate::cg_core::rng::Rng;
        use crate::cg_search::Game;

        use crate::uttt_engine::board::{Board, Status};
        use crate::uttt_engine::moves::{Move, MoveList};

        impl Game for Board {
            type Move = Move;

            fn to_move(&self) -> usize {
                Board::to_move(self)
            }

            fn legal_moves(&self, moves: &mut Vec<Move>) {
                let mut list = MoveList::new();
                Board::legal_moves(self, &mut list);
                moves.clear();
                moves.extend_from_slice(&list);
            }

            fn play(&mut self, mv: Move) {
                Board::play(self, mv);
            }

            fn score(&self) -> Option<f64> {
                score(self.status())
            }

            fn playout(&mut self, rng: &mut Rng) -> f64 {
                score(self.random_playout(rng)).expect("a playout ends the game")
            }
        }

        /// Seat 0's score for a game status: 1, 0.5 or 0 once the game is over.
        pub fn score(status: Status) -> Option<f64> {
            match status {
                Status::Ongoing => None,
                Status::Win(0) => Some(1.0),
                Status::Win(_) => Some(0.0),
                Status::Draw => Some(0.5),
            }
        }
    }

    pub use board::{Board, Status};
    pub use moves::{Move, MoveList};
}
