//! Generated by `uttt-trainer fit-policy`: local run of 2026-10-08: 2,000 games at 10,000 iterations (selfplay seeds 101 and 202, 1,000 games each), temperature 0.5.

/// Weights of the playout policy's move classes (ADR 0016); see
/// `uttt_engine::board::PlayoutPolicy`.
pub const PLAYOUT_WEIGHTS: [u32; 32] = [
    800, 10000, 7504, 2816, 60, 1026, 618, 2201, 313, 1891, 1815, 1727, 1070, 1070, 1070, 1070,
    460, 3859, 2582, 2999, 165, 1083, 841, 1668, 113, 756, 800, 828, 1070, 1070, 1070, 1070,
];
