//! Bundles a bot and the workspace crates it uses into one Rust file that
//! CodinGame accepts.
//!
//! The bundler works on text. By default it then removes comments,
//! indentation and blank lines to save room under CodinGame's size limit
//! (ADR 0016); `--keep-comments` keeps a bundle that reads like the
//! sources. It relies on these conventions, which keep the text
//! transformations safe:
//!
//! - Modules live in files declared with `mod name;` on a line of their own
//!   (optionally `pub` or `pub(...)`). `#[path]` attributes are not allowed.
//! - A `mod name;` line preceded by a `#[cfg(test)]` line is dropped, so tests
//!   belong in their own files (`#[cfg(test)] mod tests;`).
//! - A bot may only depend on workspace crates, and those crates may only
//!   depend on other workspace crates: CodinGame offers no crates.io.
//! - Code refers to other workspace crates by their crate name (`cg_core::`)
//!   and to its own crate with `crate::` or `$crate::`.
//!
//! Each library becomes a module at the root of the bundle (`mod cg_core
//! { ... }`), and paths are rewritten to match: `cg_core::x` becomes
//! `crate::cg_core::x`, and `crate::x` inside `cg_core` becomes
//! `crate::cg_core::x`.

pub mod expand;
pub mod minify;
pub mod plan;
pub mod rewrite;

use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};

use crate::plan::Plan;

/// CodinGame's code size limit, in bytes.
pub const SIZE_LIMIT: usize = 100_000;

/// How a bundle is written.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Options {
    /// Formats the code with `rustfmt`, which also checks that it parses.
    pub format: bool,
    /// Removes comments, indentation and blank lines from the code.
    pub strip: bool,
}

impl Default for Options {
    fn default() -> Self {
        Self {
            format: true,
            strip: true,
        }
    }
}

/// Builds the bundled source of `plan`. The header comment, which names
/// the package, is always kept.
pub fn bundle(plan: &Plan, options: Options) -> Result<String, String> {
    let libraries: Vec<String> = plan.libraries.iter().map(|lib| lib.name.clone()).collect();
    let mut header = format!(
        "// Bundled by cg-bundler from the `{}` package. Do not edit this file:\n\
         // change the sources in the repository and bundle again.\n",
        plan.package
    );
    if !libraries.is_empty() {
        header.push_str(&format!(
            "// Workspace crates included below: {}.\n",
            libraries.join(", ")
        ));
    }
    if options.strip {
        header.push_str("// Comments and indentation were removed to save space.\n");
    }

    let bot = expand::expand_crate(&plan.bot.root)?;
    let mut code = rewrite::rewrite(&bot, None, &libraries);

    for library in &plan.libraries {
        let source = expand::expand_crate(&library.root)?;
        // A bot rarely uses all of a library.
        code.push_str("\n#[allow(dead_code, unused_imports)]\n");
        code.push_str(&format!("mod {} {{\n", library.name));
        code.push_str(&rewrite::rewrite(&source, Some(&library.name), &libraries));
        code.push_str("}\n");
    }

    if options.format {
        code = rustfmt(&code)?;
    }
    if options.strip {
        code = minify::strip(&code);
    } else {
        header.push('\n');
    }
    Ok(header + &code)
}

/// Formats Rust source with `rustfmt`, 2021 edition.
fn rustfmt(source: &str) -> Result<String, String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2021", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|err| format!("cannot run rustfmt ({err}); use --no-format to skip it"))?;
    let mut stdin = child.stdin.take().expect("stdin is piped");
    let input = source.to_string();
    // Write from another thread so a large output cannot block the input.
    let writer = std::thread::spawn(move || stdin.write_all(input.as_bytes()));
    let output = child
        .wait_with_output()
        .map_err(|err| format!("rustfmt failed: {err}"))?;
    writer
        .join()
        .map_err(|_| "rustfmt input thread panicked".to_string())?
        .map_err(|err| format!("cannot send the bundle to rustfmt: {err}"))?;
    if !output.status.success() {
        return Err(format!(
            "rustfmt rejected the bundle, so it would not compile either:\n{}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    String::from_utf8(output.stdout).map_err(|err| format!("rustfmt output is not UTF-8: {err}"))
}

/// Bundles the bot package `package` of the workspace containing `manifest`.
pub fn bundle_package(
    package: &str,
    manifest: Option<&Path>,
    options: Options,
) -> Result<String, String> {
    let plan = plan::plan(package, manifest)?;
    bundle(&plan, options)
}
